set spell spelllang=de,en
set background=dark
set autoindent
set nosmartindent
set listchars=tab:»\ ,trail:.,extends:#
set list
set ts=3
set number
set scrolloff=5
set sidescrolloff=5
set laststatus=2
set incsearch
set mouse=
set dir=~/.vimhist/
set backupdir=~/.vimhist/bak
set showcmd
highlight Normal ctermfg=white ctermbg=17
nnoremap <silent><cr> :nohlsearch<CR>
vnoremap < <gv
vnoremap > >gv
nnoremap <c-down> <c-w><c-j>
nnoremap <c-up> <c-w><c-k>
nnoremap <c-right> <c-w><c-l>
nnoremap <c-left> <c-w><c-h>
nnoremap <a-left> gT
nnoremap <a-right> gt
let mapleader=","

hi CursorColumn ctermbg=black

set winaltkeys=no
set noai
set cursorline
set cursorcolumn
set si
set sw=3
set pt=<F4>
set ignorecase
set wildmenu
set hlsearch
noremap  <buffer> <silent> <Up>   gk
noremap  <buffer> <silent> <Down> gj
noremap  <buffer> <silent> <Home> g<Home>
noremap  <buffer> <silent> <End>  g<End>
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
