sensor:
  - !include sensor/bme280.yaml
  - !include sensor/bme280-dewpoint.yaml
  - !include sensor/scd41.yaml
  - !include sensor/scd41-dewpoint.yaml

button:
  - !include button/restart.yaml
  - !include button/calibrate.yaml
