# Generated by carnix 0.7.2: carnix nix --src .
{ lib, buildPlatform, buildRustCrate, fetchgit }:
let kernel = buildPlatform.parsed.kernel.name;
    abi = buildPlatform.parsed.abi.name;
    include = includedFiles: src: builtins.filterSource (path: type:
      lib.lists.any (f:
        let p = toString (src + ("/" + f)); in
        (path == p) || (type == "directory" && lib.strings.hasPrefix path p)
      ) includedFiles
    ) src;
    updateFeatures = f: up: functions: builtins.deepSeq f (lib.lists.foldl' (features: fun: fun features) (lib.attrsets.recursiveUpdate f up) functions);
    mapFeatures = features: map (fun: fun { features = features; });
    mkFeatures = feat: lib.lists.foldl (features: featureName:
      if feat.${featureName} or false then
        [ featureName ] ++ features
      else
        features
    ) [] (builtins.attrNames feat);
in
rec {
  tasktree = f: tasktree_0_1_0 { features = tasktree_0_1_0_features { tasktree_0_1_0 = f; }; };
  __all = [ (tasktree {}) ];
  aho_corasick_0_6_6_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "aho-corasick";
    version = "0.6.6";
    authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
    sha256 = "0ap5lv1q6ylmzq70bjgg66dsa6p9926gwv2q4z0chfjnii8hczq8";
    libName = "aho_corasick";
    crateBin = [ {  name = "aho-corasick-dot";  path = "src/main.rs"; } ];
    inherit dependencies buildDependencies features;
  };
  atk_sys_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "atk-sys";
    version = "0.3.4";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "0185ggdpwi9rg9spk4ff3v3sz01grbaihxlsim89i7gndj20g4ah";
    libName = "atk_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  bitflags_0_5_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "bitflags";
    version = "0.5.0";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0bgw1kiy121kikjrwj6zsd7l8n1gg1jirivzkc7zpjsvqa3p0hla";
    inherit dependencies buildDependencies features;
  };
  bitflags_0_8_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "bitflags";
    version = "0.8.2";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0whaj3969ysqxzk620sk1isvq6vh85516f2fplvqjrw3syz44sb2";
    inherit dependencies buildDependencies features;
  };
  c_vec_1_2_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "c_vec";
    version = "1.2.1";
    authors = [ "Guillaume Gomez <guillaume1.gomez@gmail.com>" ];
    sha256 = "15gm72wx9kd0n51454i58rmpkmig8swghrj2440frxxi9kqg97xd";
    inherit dependencies buildDependencies features;
  };
  cairo_rs_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "cairo-rs";
    version = "0.1.3";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "17wp5wh1jvn2ny8s6fckvbwn0x8ixha6xrqas1bqxd9ygm5g58w1";
    libName = "cairo";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  cairo_sys_rs_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "cairo-sys-rs";
    version = "0.3.4";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "1fzxshv7vysnnc2nywla6gj3hh00nr6cz1ak0mrxkg65rzrgxkww";
    libName = "cairo_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  cfg_if_0_1_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "cfg-if";
    version = "0.1.4";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "0n5baxk53dvqjymzwynq55wb805b24390qx1n16zi8fjzq90j7k4";
    inherit dependencies buildDependencies features;
  };
  chrono_0_2_25_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "chrono";
    version = "0.2.25";
    authors = [ "Kang Seonghoon <public+rust@mearie.org>" ];
    sha256 = "0gsvqk8cnmm43qj3xyngqvfqh50cbdbqas7ik0wjgnvknirmmca7";
    inherit dependencies buildDependencies features;
  };
  dtoa_0_4_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "dtoa";
    version = "0.4.3";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "1xysdxdm24sk5ysim7lps4r2qaxfnj0sbakhmps4d42yssx30cw8";
    inherit dependencies buildDependencies features;
  };
  gdk_0_5_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "gdk";
    version = "0.5.3";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "1745lxr0sgvs7kfkq71ri5brbxkxrfm5hxmz6ajywcpgx5zkk1w8";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  gdk_pixbuf_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "gdk-pixbuf";
    version = "0.1.3";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "0ndq5fqhh3j2vax9vxhgslrvhpia8w4b2pczlpnaixiwy0jy3wwz";
    libName = "gdk_pixbuf";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  gdk_pixbuf_sys_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "gdk-pixbuf-sys";
    version = "0.3.4";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "0rp98zx7pcibp6wzxnwfpggvcbbnnlvnxgqsgqzdwhjzdlqk963i";
    libName = "gdk_pixbuf_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  gdk_sys_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "gdk-sys";
    version = "0.3.4";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "1c59xij0lyxmmicwv6q8d91m3aikfqmva63rn6qr04rq141rkqz3";
    libName = "gdk_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  gio_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "gio";
    version = "0.1.3";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "1y4vrb41cwsqv8zhdqaddlsvn9v8x1ainqmcim169wr5lkk6ja62";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  gio_sys_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "gio-sys";
    version = "0.3.4";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "1w1d68v5mk93s9cz0m499wrgnkx3ksvy8hgfwncq2lqxvray9z7m";
    libName = "gio_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  glib_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "glib";
    version = "0.1.3";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "1j2zwsnxlfdrj8wdi8yp3zl5l9nydsifgxspnwl6ijq3ywnjhcpa";
    inherit dependencies buildDependencies features;
  };
  glib_sys_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "glib-sys";
    version = "0.3.4";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "06ymp4ljrjnb7cly0bixy3svxgnwpbx79499889dqakpfs7566rc";
    libName = "glib_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  gobject_sys_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "gobject-sys";
    version = "0.3.4";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "0rrk3c94myhspyl3iq7k4kcm72zxl8bk3r7kvqv2f9lf6y820giw";
    libName = "gobject_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  gtk_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "gtk";
    version = "0.1.3";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "0zs95szbmxpg9kndd756pa9xwqqq3xw0jmmqp23lr55znxv087ss";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  gtk_sys_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "gtk-sys";
    version = "0.3.4";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "04fqaxynjmc4vjpx7x2nbwck2s7vj8h299xb5j5l0njnbj50b7hd";
    libName = "gtk_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  itoa_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "itoa";
    version = "0.3.4";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "1nfkzz6vrgj0d9l3yzjkkkqzdgs68y294fjdbl7jq118qi8xc9d9";
    inherit dependencies buildDependencies features;
  };
  lazy_static_0_2_11_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "lazy_static";
    version = "0.2.11";
    authors = [ "Marvin Löbel <loebel.marvin@gmail.com>" ];
    sha256 = "1x6871cvpy5b96yv4c7jvpq316fp5d4609s9py7qk6cd6x9k34vm";
    inherit dependencies buildDependencies features;
  };
  lazy_static_1_0_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "lazy_static";
    version = "1.0.2";
    authors = [ "Marvin Löbel <loebel.marvin@gmail.com>" ];
    sha256 = "0ix4dmy6zb4v3m75l4alg84fk06y145z52z9pyysc9labw2x5r3r";
    inherit dependencies buildDependencies features;
  };
  libc_0_2_42_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "libc";
    version = "0.2.42";
    authors = [ "The Rust Project Developers" ];
    sha256 = "064v49hz1zpl081w8c4vwikrkhaxp06y4i9l7x7wx6bjpwp19pjx";
    inherit dependencies buildDependencies features;
  };
  log_0_3_9_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "log";
    version = "0.3.9";
    authors = [ "The Rust Project Developers" ];
    sha256 = "19i9pwp7lhaqgzangcpw00kc3zsgcqcx84crv07xgz3v7d3kvfa2";
    inherit dependencies buildDependencies features;
  };
  log_0_4_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "log";
    version = "0.4.3";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1gdmwrbm7s18zcdz4lcdhz975m4gwhi854c7j1rvj1gsr8aca250";
    inherit dependencies buildDependencies features;
  };
  memchr_2_0_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "memchr";
    version = "2.0.1";
    authors = [ "Andrew Gallant <jamslam@gmail.com>" "bluss" ];
    sha256 = "0ls2y47rjwapjdax6bp974gdp06ggm1v8d1h69wyydmh1nhgm5gr";
    inherit dependencies buildDependencies features;
  };
  num_0_1_42_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "num";
    version = "0.1.42";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1632gczzrmmxdsj3jignwcr793jq8vxw3qkdzpdvbip3vaf1ljgq";
    inherit dependencies buildDependencies features;
  };
  num_integer_0_1_39_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "num-integer";
    version = "0.1.39";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1f42ls46cghs13qfzgbd7syib2zc6m7hlmv1qlar6c9mdxapvvbg";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  num_iter_0_1_37_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "num-iter";
    version = "0.1.37";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1rglyvi4yjfxfvfm2s7i60g1dkl5xmsyi77g6vy53jb11r6wl8ly";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  num_traits_0_1_43_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "num-traits";
    version = "0.1.43";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1zdzx78vrcg3f39w94pqjs1mwxl1phyv7843hwgwkzggwcxhhf6s";
    inherit dependencies buildDependencies features;
  };
  num_traits_0_2_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "num-traits";
    version = "0.2.5";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0ql203ca6lzppksy4fsfnpz3kq96vwlwvyn3ahvnd9g6k9f5ncj0";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  pango_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "pango";
    version = "0.1.3";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "19i470lwxxk91zidr881w3ggf6kg1s05my9cgn9dgnybr90y9sw9";
    inherit dependencies buildDependencies features;
  };
  pango_sys_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "pango-sys";
    version = "0.3.4";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "0wllm1ydr0if5qh1rybipdj3ry28ha1va00bn6vskb757x2f1mgx";
    libName = "pango_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  pkg_config_0_3_12_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "pkg-config";
    version = "0.3.12";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "0k343rlyv9qmplxwxn8clzkyx1zbplhnvm0psjl6s111fjqmgsgh";
    inherit dependencies buildDependencies features;
  };
  quote_0_3_15_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "quote";
    version = "0.3.15";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "09il61jv4kd1360spaj46qwyl21fv1qz18fsv2jra8wdnlgl5jsg";
    inherit dependencies buildDependencies features;
  };
  redox_syscall_0_1_40_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "redox_syscall";
    version = "0.1.40";
    authors = [ "Jeremy Soller <jackpot51@gmail.com>" ];
    sha256 = "132rnhrq49l3z7gjrwj2zfadgw6q0355s6a7id7x7c0d7sk72611";
    libName = "syscall";
    inherit dependencies buildDependencies features;
  };
  regex_0_2_11_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "regex";
    version = "0.2.11";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0r50cymxdqp0fv1dxd22mjr6y32q450nwacd279p9s7lh0cafijj";
    inherit dependencies buildDependencies features;
  };
  regex_syntax_0_5_6_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "regex-syntax";
    version = "0.5.6";
    authors = [ "The Rust Project Developers" ];
    sha256 = "10vf3r34bgjnbrnqd5aszn35bjvm8insw498l1vjy8zx5yms3427";
    inherit dependencies buildDependencies features;
  };
  serde_0_9_15_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "serde";
    version = "0.9.15";
    authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" ];
    sha256 = "0rlflkc57kvy69hnhj4arfsj7ic4hpihxsb00zg5lkdxfj5qjx9b";
    inherit dependencies buildDependencies features;
  };
  serde_codegen_internals_0_14_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "serde_codegen_internals";
    version = "0.14.2";
    authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" ];
    sha256 = "1v7kbxfhg42nmxwbchd6wgp1b3q5xfay3vii4f4jf0h1grn8mr9r";
    inherit dependencies buildDependencies features;
  };
  serde_derive_0_9_15_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "serde_derive";
    version = "0.9.15";
    authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" ];
    sha256 = "11f78k33nvyfhbi2j4qjxz42l8d7s2nhcfarp4g4izvh81yq7hgw";
    procMacro = true;
    inherit dependencies buildDependencies features;
  };
  serde_json_0_9_10_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "serde_json";
    version = "0.9.10";
    authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" ];
    sha256 = "0g6bxlfnvf2miicnsizyrxm686rfval6gbss1i2qcna8msfwc005";
    inherit dependencies buildDependencies features;
  };
  syn_0_11_11_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "syn";
    version = "0.11.11";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "0yw8ng7x1dn5a6ykg0ib49y7r9nhzgpiq2989rqdp7rdz3n85502";
    inherit dependencies buildDependencies features;
  };
  synom_0_11_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "synom";
    version = "0.11.3";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "1l6d1s9qjfp6ng2s2z8219igvlv7gyk8gby97sdykqc1r93d8rhc";
    inherit dependencies buildDependencies features;
  };
  task_hookrs_0_3_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "task-hookrs";
    version = "0.3.0";
    authors = [ "Matthias Beyer <mail@beyermatthias.de>" "Mario Krehl <mario-krehl@gmx.de>" ];
    sha256 = "1awfd9fy1j960y8ss70s1y58kbwqg0lvzr2bq85mkbbacn6ky7v2";
    inherit dependencies buildDependencies features;
  };
  tasktree_0_1_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "tasktree";
    version = "0.1.0";
    authors = [ "Malte Brandy <malte.brandy@maralorn.de>" ];
    src = ./.;
    inherit dependencies buildDependencies features;
  };
  thread_local_0_3_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "thread_local";
    version = "0.3.5";
    authors = [ "Amanieu d'Antras <amanieu@gmail.com>" ];
    sha256 = "0mkp0sp91aqsk7brgygai4igv751r1754rsxn37mig3ag5rx8np6";
    inherit dependencies buildDependencies features;
  };
  time_0_1_40_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "time";
    version = "0.1.40";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0wgnbjamljz6bqxsd5axc4p2mmhkqfrryj4gf2yswjaxiw5dd01m";
    inherit dependencies buildDependencies features;
  };
  ucd_util_0_1_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "ucd-util";
    version = "0.1.1";
    authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
    sha256 = "02a8h3siipx52b832xc8m8rwasj6nx9jpiwfldw8hp6k205hgkn0";
    inherit dependencies buildDependencies features;
  };
  unicode_xid_0_0_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "unicode-xid";
    version = "0.0.4";
    authors = [ "erick.tryzelaar <erick.tryzelaar@gmail.com>" "kwantam <kwantam@gmail.com>" ];
    sha256 = "1dc8wkkcd3s6534s5aw4lbjn8m67flkkbnajp5bl8408wdg8rh9v";
    inherit dependencies buildDependencies features;
  };
  unreachable_1_0_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "unreachable";
    version = "1.0.0";
    authors = [ "Jonathan Reem <jonathan.reem@gmail.com>" ];
    sha256 = "1am8czbk5wwr25gbp2zr007744fxjshhdqjz9liz7wl4pnv3whcf";
    inherit dependencies buildDependencies features;
  };
  utf8_ranges_1_0_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "utf8-ranges";
    version = "1.0.0";
    authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
    sha256 = "0rzmqprwjv9yp1n0qqgahgm24872x6c0xddfym5pfndy7a36vkn0";
    inherit dependencies buildDependencies features;
  };
  uuid_0_4_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "uuid";
    version = "0.4.0";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1fzgp3ayz7g5zx4gvxkxxm9jkrllj5qlvlyp6r2an0wyqm2y9qlh";
    inherit dependencies buildDependencies features;
  };
  void_1_0_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "void";
    version = "1.0.2";
    authors = [ "Jonathan Reem <jonathan.reem@gmail.com>" ];
    sha256 = "0h1dm0dx8dhf56a83k68mijyxigqhizpskwxfdrs1drwv2cdclv3";
    inherit dependencies buildDependencies features;
  };
  winapi_0_2_8_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi";
    version = "0.2.8";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "0a45b58ywf12vb7gvj6h3j264nydynmzyqz8d8rqxsj6icqv82as";
    inherit dependencies buildDependencies features;
  };
  winapi_0_3_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi";
    version = "0.3.5";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "0cfdsxa5yf832r5i2z7dhdvnryyvhfp3nb32gpcaq502zgjdm3w6";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  winapi_i686_pc_windows_gnu_0_4_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi-i686-pc-windows-gnu";
    version = "0.4.0";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "05ihkij18r4gamjpxj4gra24514can762imjzlmak5wlzidplzrp";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  winapi_x86_64_pc_windows_gnu_0_4_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi-x86_64-pc-windows-gnu";
    version = "0.4.0";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "0n1ylmlsb8yg1v583i4xy0qmqg42275flvbc51hdqjjfjcl9vlbj";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  aho_corasick_0_6_6 = { features?(aho_corasick_0_6_6_features {}) }: aho_corasick_0_6_6_ {
    dependencies = mapFeatures features ([ memchr_2_0_1 ]);
  };
  aho_corasick_0_6_6_features = f: updateFeatures f (rec {
    aho_corasick_0_6_6.default = (f.aho_corasick_0_6_6.default or true);
    memchr_2_0_1.default = true;
  }) [ memchr_2_0_1_features ];
  atk_sys_0_3_4 = { features?(atk_sys_0_3_4_features {}) }: atk_sys_0_3_4_ {
    dependencies = mapFeatures features ([ bitflags_0_8_2 glib_sys_0_3_4 gobject_sys_0_3_4 libc_0_2_42 ]);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_12 ]);
    features = mkFeatures (features.atk_sys_0_3_4 or {});
  };
  atk_sys_0_3_4_features = f: updateFeatures f (rec {
    atk_sys_0_3_4.default = (f.atk_sys_0_3_4.default or true);
    atk_sys_0_3_4.v2_10 =
      (f.atk_sys_0_3_4.v2_10 or false) ||
      (f.atk_sys_0_3_4.v2_12 or false) ||
      (atk_sys_0_3_4.v2_12 or false);
    atk_sys_0_3_4.v2_12 =
      (f.atk_sys_0_3_4.v2_12 or false) ||
      (f.atk_sys_0_3_4.v2_14 or false) ||
      (atk_sys_0_3_4.v2_14 or false);
    atk_sys_0_3_4.v2_7_4 =
      (f.atk_sys_0_3_4.v2_7_4 or false) ||
      (f.atk_sys_0_3_4.v2_7_90 or false) ||
      (atk_sys_0_3_4.v2_7_90 or false);
    atk_sys_0_3_4.v2_7_90 =
      (f.atk_sys_0_3_4.v2_7_90 or false) ||
      (f.atk_sys_0_3_4.v2_8 or false) ||
      (atk_sys_0_3_4.v2_8 or false);
    atk_sys_0_3_4.v2_8 =
      (f.atk_sys_0_3_4.v2_8 or false) ||
      (f.atk_sys_0_3_4.v2_9_3 or false) ||
      (atk_sys_0_3_4.v2_9_3 or false);
    atk_sys_0_3_4.v2_9_3 =
      (f.atk_sys_0_3_4.v2_9_3 or false) ||
      (f.atk_sys_0_3_4.v2_9_4 or false) ||
      (atk_sys_0_3_4.v2_9_4 or false);
    atk_sys_0_3_4.v2_9_4 =
      (f.atk_sys_0_3_4.v2_9_4 or false) ||
      (f.atk_sys_0_3_4.v2_10 or false) ||
      (atk_sys_0_3_4.v2_10 or false);
    bitflags_0_8_2.default = true;
    glib_sys_0_3_4.default = true;
    gobject_sys_0_3_4.default = true;
    libc_0_2_42.default = true;
    pkg_config_0_3_12.default = true;
  }) [ bitflags_0_8_2_features glib_sys_0_3_4_features gobject_sys_0_3_4_features libc_0_2_42_features pkg_config_0_3_12_features ];
  bitflags_0_5_0 = { features?(bitflags_0_5_0_features {}) }: bitflags_0_5_0_ {
    features = mkFeatures (features.bitflags_0_5_0 or {});
  };
  bitflags_0_5_0_features = f: updateFeatures f (rec {
    bitflags_0_5_0.default = (f.bitflags_0_5_0.default or true);
  }) [];
  bitflags_0_8_2 = { features?(bitflags_0_8_2_features {}) }: bitflags_0_8_2_ {
    features = mkFeatures (features.bitflags_0_8_2 or {});
  };
  bitflags_0_8_2_features = f: updateFeatures f (rec {
    bitflags_0_8_2.default = (f.bitflags_0_8_2.default or true);
    bitflags_0_8_2.i128 =
      (f.bitflags_0_8_2.i128 or false) ||
      (f.bitflags_0_8_2.unstable or false) ||
      (bitflags_0_8_2.unstable or false);
  }) [];
  c_vec_1_2_1 = { features?(c_vec_1_2_1_features {}) }: c_vec_1_2_1_ {};
  c_vec_1_2_1_features = f: updateFeatures f (rec {
    c_vec_1_2_1.default = (f.c_vec_1_2_1.default or true);
  }) [];
  cairo_rs_0_1_3 = { features?(cairo_rs_0_1_3_features {}) }: cairo_rs_0_1_3_ {
    dependencies = mapFeatures features ([ c_vec_1_2_1 cairo_sys_rs_0_3_4 libc_0_2_42 ]
      ++ (if features.cairo_rs_0_1_3.glib or false then [ glib_0_1_3 ] else []))
      ++ (if kernel == "windows" then mapFeatures features ([ winapi_0_2_8 ]) else []);
    buildDependencies = mapFeatures features ([]);
    features = mkFeatures (features.cairo_rs_0_1_3 or {});
  };
  cairo_rs_0_1_3_features = f: updateFeatures f (rec {
    c_vec_1_2_1.default = true;
    cairo_rs_0_1_3.default = (f.cairo_rs_0_1_3.default or true);
    cairo_rs_0_1_3.glib =
      (f.cairo_rs_0_1_3.glib or false) ||
      (f.cairo_rs_0_1_3.default or false) ||
      (cairo_rs_0_1_3.default or false);
    cairo_rs_0_1_3.gtk-rs-lgpl-docs =
      (f.cairo_rs_0_1_3.gtk-rs-lgpl-docs or false) ||
      (f.cairo_rs_0_1_3.embed-lgpl-docs or false) ||
      (cairo_rs_0_1_3.embed-lgpl-docs or false) ||
      (f.cairo_rs_0_1_3.purge-lgpl-docs or false) ||
      (cairo_rs_0_1_3.purge-lgpl-docs or false);
    cairo_sys_rs_0_3_4.default = true;
    cairo_sys_rs_0_3_4.png =
      (f.cairo_sys_rs_0_3_4.png or false) ||
      (cairo_rs_0_1_3.png or false) ||
      (f.cairo_rs_0_1_3.png or false);
    cairo_sys_rs_0_3_4.v1_12 =
      (f.cairo_sys_rs_0_3_4.v1_12 or false) ||
      (cairo_rs_0_1_3.v1_12 or false) ||
      (f.cairo_rs_0_1_3.v1_12 or false);
    cairo_sys_rs_0_3_4.xcb =
      (f.cairo_sys_rs_0_3_4.xcb or false) ||
      (cairo_rs_0_1_3.xcb or false) ||
      (f.cairo_rs_0_1_3.xcb or false);
    glib_0_1_3.default = true;
    libc_0_2_42.default = true;
    winapi_0_2_8.default = true;
  }) [ c_vec_1_2_1_features cairo_sys_rs_0_3_4_features glib_0_1_3_features libc_0_2_42_features winapi_0_2_8_features ];
  cairo_sys_rs_0_3_4 = { features?(cairo_sys_rs_0_3_4_features {}) }: cairo_sys_rs_0_3_4_ {
    dependencies = mapFeatures features ([ libc_0_2_42 ])
      ++ (if kernel == "windows" then mapFeatures features ([ winapi_0_2_8 ]) else []);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_12 ]);
    features = mkFeatures (features.cairo_sys_rs_0_3_4 or {});
  };
  cairo_sys_rs_0_3_4_features = f: updateFeatures f (rec {
    cairo_sys_rs_0_3_4.default = (f.cairo_sys_rs_0_3_4.default or true);
    cairo_sys_rs_0_3_4.v1_12 =
      (f.cairo_sys_rs_0_3_4.v1_12 or false) ||
      (f.cairo_sys_rs_0_3_4.v1_14 or false) ||
      (cairo_sys_rs_0_3_4.v1_14 or false);
    cairo_sys_rs_0_3_4.x11 =
      (f.cairo_sys_rs_0_3_4.x11 or false) ||
      (f.cairo_sys_rs_0_3_4.xlib or false) ||
      (cairo_sys_rs_0_3_4.xlib or false);
    libc_0_2_42.default = true;
    pkg_config_0_3_12.default = true;
    winapi_0_2_8.default = true;
  }) [ libc_0_2_42_features pkg_config_0_3_12_features winapi_0_2_8_features ];
  cfg_if_0_1_4 = { features?(cfg_if_0_1_4_features {}) }: cfg_if_0_1_4_ {};
  cfg_if_0_1_4_features = f: updateFeatures f (rec {
    cfg_if_0_1_4.default = (f.cfg_if_0_1_4.default or true);
  }) [];
  chrono_0_2_25 = { features?(chrono_0_2_25_features {}) }: chrono_0_2_25_ {
    dependencies = mapFeatures features ([ num_0_1_42 time_0_1_40 ]);
  };
  chrono_0_2_25_features = f: updateFeatures f (rec {
    chrono_0_2_25.default = (f.chrono_0_2_25.default or true);
    num_0_1_42.default = (f.num_0_1_42.default or false);
    time_0_1_40.default = true;
  }) [ num_0_1_42_features time_0_1_40_features ];
  dtoa_0_4_3 = { features?(dtoa_0_4_3_features {}) }: dtoa_0_4_3_ {};
  dtoa_0_4_3_features = f: updateFeatures f (rec {
    dtoa_0_4_3.default = (f.dtoa_0_4_3.default or true);
  }) [];
  gdk_0_5_3 = { features?(gdk_0_5_3_features {}) }: gdk_0_5_3_ {
    dependencies = mapFeatures features ([ bitflags_0_5_0 cairo_rs_0_1_3 cairo_sys_rs_0_3_4 gdk_pixbuf_0_1_3 gdk_sys_0_3_4 gio_0_1_3 glib_0_1_3 glib_sys_0_3_4 gobject_sys_0_3_4 libc_0_2_42 pango_0_1_3 ]);
    buildDependencies = mapFeatures features ([]);
    features = mkFeatures (features.gdk_0_5_3 or {});
  };
  gdk_0_5_3_features = f: updateFeatures f (rec {
    bitflags_0_5_0.default = true;
    cairo_rs_0_1_3.default = true;
    cairo_rs_0_1_3.embed-lgpl-docs =
      (f.cairo_rs_0_1_3.embed-lgpl-docs or false) ||
      (gdk_0_5_3.embed-lgpl-docs or false) ||
      (f.gdk_0_5_3.embed-lgpl-docs or false);
    cairo_rs_0_1_3.purge-lgpl-docs =
      (f.cairo_rs_0_1_3.purge-lgpl-docs or false) ||
      (gdk_0_5_3.purge-lgpl-docs or false) ||
      (f.gdk_0_5_3.purge-lgpl-docs or false);
    cairo_rs_0_1_3.v1_12 =
      (f.cairo_rs_0_1_3.v1_12 or false) ||
      (gdk_0_5_3.v3_10 or false) ||
      (f.gdk_0_5_3.v3_10 or false);
    cairo_sys_rs_0_3_4.default = true;
    gdk_0_5_3.default = (f.gdk_0_5_3.default or true);
    gdk_0_5_3.gtk-rs-lgpl-docs =
      (f.gdk_0_5_3.gtk-rs-lgpl-docs or false) ||
      (f.gdk_0_5_3.embed-lgpl-docs or false) ||
      (gdk_0_5_3.embed-lgpl-docs or false) ||
      (f.gdk_0_5_3.purge-lgpl-docs or false) ||
      (gdk_0_5_3.purge-lgpl-docs or false);
    gdk_0_5_3.v3_10 =
      (f.gdk_0_5_3.v3_10 or false) ||
      (f.gdk_0_5_3.v3_12 or false) ||
      (gdk_0_5_3.v3_12 or false);
    gdk_0_5_3.v3_12 =
      (f.gdk_0_5_3.v3_12 or false) ||
      (f.gdk_0_5_3.v3_14 or false) ||
      (gdk_0_5_3.v3_14 or false);
    gdk_0_5_3.v3_14 =
      (f.gdk_0_5_3.v3_14 or false) ||
      (f.gdk_0_5_3.v3_16 or false) ||
      (gdk_0_5_3.v3_16 or false);
    gdk_0_5_3.v3_16 =
      (f.gdk_0_5_3.v3_16 or false) ||
      (f.gdk_0_5_3.v3_18 or false) ||
      (gdk_0_5_3.v3_18 or false);
    gdk_0_5_3.v3_18 =
      (f.gdk_0_5_3.v3_18 or false) ||
      (f.gdk_0_5_3.v3_20 or false) ||
      (gdk_0_5_3.v3_20 or false);
    gdk_0_5_3.v3_20 =
      (f.gdk_0_5_3.v3_20 or false) ||
      (f.gdk_0_5_3.v3_22 or false) ||
      (gdk_0_5_3.v3_22 or false);
    gdk_0_5_3.v3_6 =
      (f.gdk_0_5_3.v3_6 or false) ||
      (f.gdk_0_5_3.v3_8 or false) ||
      (gdk_0_5_3.v3_8 or false);
    gdk_0_5_3.v3_8 =
      (f.gdk_0_5_3.v3_8 or false) ||
      (f.gdk_0_5_3.v3_10 or false) ||
      (gdk_0_5_3.v3_10 or false);
    gdk_pixbuf_0_1_3.default = true;
    gdk_pixbuf_0_1_3.embed-lgpl-docs =
      (f.gdk_pixbuf_0_1_3.embed-lgpl-docs or false) ||
      (gdk_0_5_3.embed-lgpl-docs or false) ||
      (f.gdk_0_5_3.embed-lgpl-docs or false);
    gdk_pixbuf_0_1_3.purge-lgpl-docs =
      (f.gdk_pixbuf_0_1_3.purge-lgpl-docs or false) ||
      (gdk_0_5_3.purge-lgpl-docs or false) ||
      (f.gdk_0_5_3.purge-lgpl-docs or false);
    gdk_pixbuf_0_1_3.v2_28 =
      (f.gdk_pixbuf_0_1_3.v2_28 or false) ||
      (gdk_0_5_3.v3_8 or false) ||
      (f.gdk_0_5_3.v3_8 or false);
    gdk_pixbuf_0_1_3.v2_30 =
      (f.gdk_pixbuf_0_1_3.v2_30 or false) ||
      (gdk_0_5_3.v3_14 or false) ||
      (f.gdk_0_5_3.v3_14 or false);
    gdk_sys_0_3_4.default = true;
    gdk_sys_0_3_4.v3_10 =
      (f.gdk_sys_0_3_4.v3_10 or false) ||
      (gdk_0_5_3.v3_10 or false) ||
      (f.gdk_0_5_3.v3_10 or false);
    gdk_sys_0_3_4.v3_12 =
      (f.gdk_sys_0_3_4.v3_12 or false) ||
      (gdk_0_5_3.v3_12 or false) ||
      (f.gdk_0_5_3.v3_12 or false);
    gdk_sys_0_3_4.v3_14 =
      (f.gdk_sys_0_3_4.v3_14 or false) ||
      (gdk_0_5_3.v3_14 or false) ||
      (f.gdk_0_5_3.v3_14 or false);
    gdk_sys_0_3_4.v3_16 =
      (f.gdk_sys_0_3_4.v3_16 or false) ||
      (gdk_0_5_3.v3_16 or false) ||
      (f.gdk_0_5_3.v3_16 or false);
    gdk_sys_0_3_4.v3_18 =
      (f.gdk_sys_0_3_4.v3_18 or false) ||
      (gdk_0_5_3.v3_18 or false) ||
      (f.gdk_0_5_3.v3_18 or false);
    gdk_sys_0_3_4.v3_20 =
      (f.gdk_sys_0_3_4.v3_20 or false) ||
      (gdk_0_5_3.v3_20 or false) ||
      (f.gdk_0_5_3.v3_20 or false);
    gdk_sys_0_3_4.v3_22 =
      (f.gdk_sys_0_3_4.v3_22 or false) ||
      (gdk_0_5_3.v3_22 or false) ||
      (f.gdk_0_5_3.v3_22 or false);
    gdk_sys_0_3_4.v3_6 =
      (f.gdk_sys_0_3_4.v3_6 or false) ||
      (gdk_0_5_3.v3_6 or false) ||
      (f.gdk_0_5_3.v3_6 or false);
    gdk_sys_0_3_4.v3_8 =
      (f.gdk_sys_0_3_4.v3_8 or false) ||
      (gdk_0_5_3.v3_8 or false) ||
      (f.gdk_0_5_3.v3_8 or false);
    gio_0_1_3.default = true;
    gio_0_1_3.embed-lgpl-docs =
      (f.gio_0_1_3.embed-lgpl-docs or false) ||
      (gdk_0_5_3.embed-lgpl-docs or false) ||
      (f.gdk_0_5_3.embed-lgpl-docs or false);
    gio_0_1_3.purge-lgpl-docs =
      (f.gio_0_1_3.purge-lgpl-docs or false) ||
      (gdk_0_5_3.purge-lgpl-docs or false) ||
      (f.gdk_0_5_3.purge-lgpl-docs or false);
    gio_0_1_3.v2_34 =
      (f.gio_0_1_3.v2_34 or false) ||
      (gdk_0_5_3.v3_8 or false) ||
      (f.gdk_0_5_3.v3_8 or false);
    gio_0_1_3.v2_36 =
      (f.gio_0_1_3.v2_36 or false) ||
      (gdk_0_5_3.v3_10 or false) ||
      (f.gdk_0_5_3.v3_10 or false);
    gio_0_1_3.v2_38 =
      (f.gio_0_1_3.v2_38 or false) ||
      (gdk_0_5_3.v3_12 or false) ||
      (f.gdk_0_5_3.v3_12 or false);
    gio_0_1_3.v2_40 =
      (f.gio_0_1_3.v2_40 or false) ||
      (gdk_0_5_3.v3_14 or false) ||
      (f.gdk_0_5_3.v3_14 or false);
    gio_0_1_3.v2_42 =
      (f.gio_0_1_3.v2_42 or false) ||
      (gdk_0_5_3.v3_16 or false) ||
      (f.gdk_0_5_3.v3_16 or false);
    gio_0_1_3.v2_44 =
      (f.gio_0_1_3.v2_44 or false) ||
      (gdk_0_5_3.v3_18 or false) ||
      (f.gdk_0_5_3.v3_18 or false);
    gio_0_1_3.v2_48 =
      (f.gio_0_1_3.v2_48 or false) ||
      (gdk_0_5_3.v3_20 or false) ||
      (f.gdk_0_5_3.v3_20 or false);
    glib_0_1_3.default = true;
    glib_sys_0_3_4.default = true;
    gobject_sys_0_3_4.default = true;
    libc_0_2_42.default = true;
    pango_0_1_3.default = true;
    pango_0_1_3.v1_32_4 =
      (f.pango_0_1_3.v1_32_4 or false) ||
      (gdk_0_5_3.v3_8 or false) ||
      (f.gdk_0_5_3.v3_8 or false);
    pango_0_1_3.v1_34 =
      (f.pango_0_1_3.v1_34 or false) ||
      (gdk_0_5_3.v3_14 or false) ||
      (f.gdk_0_5_3.v3_14 or false);
  }) [ bitflags_0_5_0_features cairo_rs_0_1_3_features cairo_sys_rs_0_3_4_features gdk_pixbuf_0_1_3_features gdk_sys_0_3_4_features gio_0_1_3_features glib_0_1_3_features glib_sys_0_3_4_features gobject_sys_0_3_4_features libc_0_2_42_features pango_0_1_3_features ];
  gdk_pixbuf_0_1_3 = { features?(gdk_pixbuf_0_1_3_features {}) }: gdk_pixbuf_0_1_3_ {
    dependencies = mapFeatures features ([ gdk_pixbuf_sys_0_3_4 glib_0_1_3 libc_0_2_42 ]);
    buildDependencies = mapFeatures features ([]);
    features = mkFeatures (features.gdk_pixbuf_0_1_3 or {});
  };
  gdk_pixbuf_0_1_3_features = f: updateFeatures f (rec {
    gdk_pixbuf_0_1_3.default = (f.gdk_pixbuf_0_1_3.default or true);
    gdk_pixbuf_0_1_3.gtk-rs-lgpl-docs =
      (f.gdk_pixbuf_0_1_3.gtk-rs-lgpl-docs or false) ||
      (f.gdk_pixbuf_0_1_3.embed-lgpl-docs or false) ||
      (gdk_pixbuf_0_1_3.embed-lgpl-docs or false) ||
      (f.gdk_pixbuf_0_1_3.purge-lgpl-docs or false) ||
      (gdk_pixbuf_0_1_3.purge-lgpl-docs or false);
    gdk_pixbuf_0_1_3.v2_28 =
      (f.gdk_pixbuf_0_1_3.v2_28 or false) ||
      (f.gdk_pixbuf_0_1_3.v2_30 or false) ||
      (gdk_pixbuf_0_1_3.v2_30 or false);
    gdk_pixbuf_0_1_3.v2_30 =
      (f.gdk_pixbuf_0_1_3.v2_30 or false) ||
      (f.gdk_pixbuf_0_1_3.v2_32 or false) ||
      (gdk_pixbuf_0_1_3.v2_32 or false);
    gdk_pixbuf_0_1_3.v2_32 =
      (f.gdk_pixbuf_0_1_3.v2_32 or false) ||
      (f.gdk_pixbuf_0_1_3.v2_36 or false) ||
      (gdk_pixbuf_0_1_3.v2_36 or false);
    gdk_pixbuf_sys_0_3_4.default = true;
    gdk_pixbuf_sys_0_3_4.v2_28 =
      (f.gdk_pixbuf_sys_0_3_4.v2_28 or false) ||
      (gdk_pixbuf_0_1_3.v2_28 or false) ||
      (f.gdk_pixbuf_0_1_3.v2_28 or false);
    gdk_pixbuf_sys_0_3_4.v2_30 =
      (f.gdk_pixbuf_sys_0_3_4.v2_30 or false) ||
      (gdk_pixbuf_0_1_3.v2_30 or false) ||
      (f.gdk_pixbuf_0_1_3.v2_30 or false);
    gdk_pixbuf_sys_0_3_4.v2_32 =
      (f.gdk_pixbuf_sys_0_3_4.v2_32 or false) ||
      (gdk_pixbuf_0_1_3.v2_32 or false) ||
      (f.gdk_pixbuf_0_1_3.v2_32 or false);
    gdk_pixbuf_sys_0_3_4.v2_36 =
      (f.gdk_pixbuf_sys_0_3_4.v2_36 or false) ||
      (gdk_pixbuf_0_1_3.v2_36 or false) ||
      (f.gdk_pixbuf_0_1_3.v2_36 or false);
    glib_0_1_3.default = true;
    libc_0_2_42.default = true;
  }) [ gdk_pixbuf_sys_0_3_4_features glib_0_1_3_features libc_0_2_42_features ];
  gdk_pixbuf_sys_0_3_4 = { features?(gdk_pixbuf_sys_0_3_4_features {}) }: gdk_pixbuf_sys_0_3_4_ {
    dependencies = mapFeatures features ([ bitflags_0_8_2 gio_sys_0_3_4 glib_sys_0_3_4 gobject_sys_0_3_4 libc_0_2_42 ]);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_12 ]);
    features = mkFeatures (features.gdk_pixbuf_sys_0_3_4 or {});
  };
  gdk_pixbuf_sys_0_3_4_features = f: updateFeatures f (rec {
    bitflags_0_8_2.default = true;
    gdk_pixbuf_sys_0_3_4.default = (f.gdk_pixbuf_sys_0_3_4.default or true);
    gdk_pixbuf_sys_0_3_4.v2_28 =
      (f.gdk_pixbuf_sys_0_3_4.v2_28 or false) ||
      (f.gdk_pixbuf_sys_0_3_4.v2_30 or false) ||
      (gdk_pixbuf_sys_0_3_4.v2_30 or false);
    gdk_pixbuf_sys_0_3_4.v2_30 =
      (f.gdk_pixbuf_sys_0_3_4.v2_30 or false) ||
      (f.gdk_pixbuf_sys_0_3_4.v2_32 or false) ||
      (gdk_pixbuf_sys_0_3_4.v2_32 or false);
    gdk_pixbuf_sys_0_3_4.v2_32 =
      (f.gdk_pixbuf_sys_0_3_4.v2_32 or false) ||
      (f.gdk_pixbuf_sys_0_3_4.v2_36 or false) ||
      (gdk_pixbuf_sys_0_3_4.v2_36 or false);
    gio_sys_0_3_4.default = true;
    glib_sys_0_3_4.default = true;
    gobject_sys_0_3_4.default = true;
    libc_0_2_42.default = true;
    pkg_config_0_3_12.default = true;
  }) [ bitflags_0_8_2_features gio_sys_0_3_4_features glib_sys_0_3_4_features gobject_sys_0_3_4_features libc_0_2_42_features pkg_config_0_3_12_features ];
  gdk_sys_0_3_4 = { features?(gdk_sys_0_3_4_features {}) }: gdk_sys_0_3_4_ {
    dependencies = mapFeatures features ([ bitflags_0_8_2 cairo_sys_rs_0_3_4 gdk_pixbuf_sys_0_3_4 gio_sys_0_3_4 glib_sys_0_3_4 gobject_sys_0_3_4 libc_0_2_42 pango_sys_0_3_4 ]);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_12 ]);
    features = mkFeatures (features.gdk_sys_0_3_4 or {});
  };
  gdk_sys_0_3_4_features = f: updateFeatures f (rec {
    bitflags_0_8_2.default = true;
    cairo_sys_rs_0_3_4.default = true;
    gdk_pixbuf_sys_0_3_4.default = true;
    gdk_sys_0_3_4.default = (f.gdk_sys_0_3_4.default or true);
    gdk_sys_0_3_4.v3_10 =
      (f.gdk_sys_0_3_4.v3_10 or false) ||
      (f.gdk_sys_0_3_4.v3_12 or false) ||
      (gdk_sys_0_3_4.v3_12 or false);
    gdk_sys_0_3_4.v3_12 =
      (f.gdk_sys_0_3_4.v3_12 or false) ||
      (f.gdk_sys_0_3_4.v3_14 or false) ||
      (gdk_sys_0_3_4.v3_14 or false);
    gdk_sys_0_3_4.v3_14 =
      (f.gdk_sys_0_3_4.v3_14 or false) ||
      (f.gdk_sys_0_3_4.v3_16 or false) ||
      (gdk_sys_0_3_4.v3_16 or false);
    gdk_sys_0_3_4.v3_16 =
      (f.gdk_sys_0_3_4.v3_16 or false) ||
      (f.gdk_sys_0_3_4.v3_18 or false) ||
      (gdk_sys_0_3_4.v3_18 or false);
    gdk_sys_0_3_4.v3_18 =
      (f.gdk_sys_0_3_4.v3_18 or false) ||
      (f.gdk_sys_0_3_4.v3_20 or false) ||
      (gdk_sys_0_3_4.v3_20 or false);
    gdk_sys_0_3_4.v3_20 =
      (f.gdk_sys_0_3_4.v3_20 or false) ||
      (f.gdk_sys_0_3_4.v3_22 or false) ||
      (gdk_sys_0_3_4.v3_22 or false);
    gdk_sys_0_3_4.v3_6 =
      (f.gdk_sys_0_3_4.v3_6 or false) ||
      (f.gdk_sys_0_3_4.v3_8 or false) ||
      (gdk_sys_0_3_4.v3_8 or false);
    gdk_sys_0_3_4.v3_8 =
      (f.gdk_sys_0_3_4.v3_8 or false) ||
      (f.gdk_sys_0_3_4.v3_10 or false) ||
      (gdk_sys_0_3_4.v3_10 or false);
    gio_sys_0_3_4.default = true;
    glib_sys_0_3_4.default = true;
    gobject_sys_0_3_4.default = true;
    libc_0_2_42.default = true;
    pango_sys_0_3_4.default = true;
    pkg_config_0_3_12.default = true;
  }) [ bitflags_0_8_2_features cairo_sys_rs_0_3_4_features gdk_pixbuf_sys_0_3_4_features gio_sys_0_3_4_features glib_sys_0_3_4_features gobject_sys_0_3_4_features libc_0_2_42_features pango_sys_0_3_4_features pkg_config_0_3_12_features ];
  gio_0_1_3 = { features?(gio_0_1_3_features {}) }: gio_0_1_3_ {
    dependencies = mapFeatures features ([ bitflags_0_5_0 gio_sys_0_3_4 glib_0_1_3 glib_sys_0_3_4 gobject_sys_0_3_4 libc_0_2_42 ]);
    buildDependencies = mapFeatures features ([]);
    features = mkFeatures (features.gio_0_1_3 or {});
  };
  gio_0_1_3_features = f: updateFeatures f (rec {
    bitflags_0_5_0.default = true;
    gio_0_1_3.default = (f.gio_0_1_3.default or true);
    gio_0_1_3.gtk-rs-lgpl-docs =
      (f.gio_0_1_3.gtk-rs-lgpl-docs or false) ||
      (f.gio_0_1_3.embed-lgpl-docs or false) ||
      (gio_0_1_3.embed-lgpl-docs or false) ||
      (f.gio_0_1_3.purge-lgpl-docs or false) ||
      (gio_0_1_3.purge-lgpl-docs or false);
    gio_0_1_3.v2_34 =
      (f.gio_0_1_3.v2_34 or false) ||
      (f.gio_0_1_3.v2_36 or false) ||
      (gio_0_1_3.v2_36 or false);
    gio_0_1_3.v2_36 =
      (f.gio_0_1_3.v2_36 or false) ||
      (f.gio_0_1_3.v2_38 or false) ||
      (gio_0_1_3.v2_38 or false);
    gio_0_1_3.v2_38 =
      (f.gio_0_1_3.v2_38 or false) ||
      (f.gio_0_1_3.v2_40 or false) ||
      (gio_0_1_3.v2_40 or false);
    gio_0_1_3.v2_40 =
      (f.gio_0_1_3.v2_40 or false) ||
      (f.gio_0_1_3.v2_42 or false) ||
      (gio_0_1_3.v2_42 or false);
    gio_0_1_3.v2_42 =
      (f.gio_0_1_3.v2_42 or false) ||
      (f.gio_0_1_3.v2_44 or false) ||
      (gio_0_1_3.v2_44 or false);
    gio_0_1_3.v2_44 =
      (f.gio_0_1_3.v2_44 or false) ||
      (f.gio_0_1_3.v2_46 or false) ||
      (gio_0_1_3.v2_46 or false);
    gio_0_1_3.v2_46 =
      (f.gio_0_1_3.v2_46 or false) ||
      (f.gio_0_1_3.v2_48 or false) ||
      (gio_0_1_3.v2_48 or false);
    gio_0_1_3.v2_48 =
      (f.gio_0_1_3.v2_48 or false) ||
      (f.gio_0_1_3.v2_50 or false) ||
      (gio_0_1_3.v2_50 or false);
    gio_sys_0_3_4.default = true;
    gio_sys_0_3_4.v2_34 =
      (f.gio_sys_0_3_4.v2_34 or false) ||
      (gio_0_1_3.v2_34 or false) ||
      (f.gio_0_1_3.v2_34 or false);
    gio_sys_0_3_4.v2_36 =
      (f.gio_sys_0_3_4.v2_36 or false) ||
      (gio_0_1_3.v2_36 or false) ||
      (f.gio_0_1_3.v2_36 or false);
    gio_sys_0_3_4.v2_38 =
      (f.gio_sys_0_3_4.v2_38 or false) ||
      (gio_0_1_3.v2_38 or false) ||
      (f.gio_0_1_3.v2_38 or false);
    gio_sys_0_3_4.v2_40 =
      (f.gio_sys_0_3_4.v2_40 or false) ||
      (gio_0_1_3.v2_40 or false) ||
      (f.gio_0_1_3.v2_40 or false);
    gio_sys_0_3_4.v2_42 =
      (f.gio_sys_0_3_4.v2_42 or false) ||
      (gio_0_1_3.v2_42 or false) ||
      (f.gio_0_1_3.v2_42 or false);
    gio_sys_0_3_4.v2_44 =
      (f.gio_sys_0_3_4.v2_44 or false) ||
      (gio_0_1_3.v2_44 or false) ||
      (f.gio_0_1_3.v2_44 or false);
    gio_sys_0_3_4.v2_46 =
      (f.gio_sys_0_3_4.v2_46 or false) ||
      (gio_0_1_3.v2_46 or false) ||
      (f.gio_0_1_3.v2_46 or false);
    gio_sys_0_3_4.v2_48 =
      (f.gio_sys_0_3_4.v2_48 or false) ||
      (gio_0_1_3.v2_48 or false) ||
      (f.gio_0_1_3.v2_48 or false);
    gio_sys_0_3_4.v2_50 =
      (f.gio_sys_0_3_4.v2_50 or false) ||
      (gio_0_1_3.v2_50 or false) ||
      (f.gio_0_1_3.v2_50 or false);
    glib_0_1_3.default = true;
    glib_sys_0_3_4.default = true;
    gobject_sys_0_3_4.default = true;
    libc_0_2_42.default = true;
  }) [ bitflags_0_5_0_features gio_sys_0_3_4_features glib_0_1_3_features glib_sys_0_3_4_features gobject_sys_0_3_4_features libc_0_2_42_features ];
  gio_sys_0_3_4 = { features?(gio_sys_0_3_4_features {}) }: gio_sys_0_3_4_ {
    dependencies = mapFeatures features ([ bitflags_0_8_2 glib_sys_0_3_4 gobject_sys_0_3_4 libc_0_2_42 ]);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_12 ]);
    features = mkFeatures (features.gio_sys_0_3_4 or {});
  };
  gio_sys_0_3_4_features = f: updateFeatures f (rec {
    bitflags_0_8_2.default = true;
    gio_sys_0_3_4.default = (f.gio_sys_0_3_4.default or true);
    gio_sys_0_3_4.v2_34 =
      (f.gio_sys_0_3_4.v2_34 or false) ||
      (f.gio_sys_0_3_4.v2_36 or false) ||
      (gio_sys_0_3_4.v2_36 or false);
    gio_sys_0_3_4.v2_36 =
      (f.gio_sys_0_3_4.v2_36 or false) ||
      (f.gio_sys_0_3_4.v2_38 or false) ||
      (gio_sys_0_3_4.v2_38 or false);
    gio_sys_0_3_4.v2_38 =
      (f.gio_sys_0_3_4.v2_38 or false) ||
      (f.gio_sys_0_3_4.v2_40 or false) ||
      (gio_sys_0_3_4.v2_40 or false);
    gio_sys_0_3_4.v2_40 =
      (f.gio_sys_0_3_4.v2_40 or false) ||
      (f.gio_sys_0_3_4.v2_42 or false) ||
      (gio_sys_0_3_4.v2_42 or false);
    gio_sys_0_3_4.v2_42 =
      (f.gio_sys_0_3_4.v2_42 or false) ||
      (f.gio_sys_0_3_4.v2_44 or false) ||
      (gio_sys_0_3_4.v2_44 or false);
    gio_sys_0_3_4.v2_44 =
      (f.gio_sys_0_3_4.v2_44 or false) ||
      (f.gio_sys_0_3_4.v2_46 or false) ||
      (gio_sys_0_3_4.v2_46 or false);
    gio_sys_0_3_4.v2_46 =
      (f.gio_sys_0_3_4.v2_46 or false) ||
      (f.gio_sys_0_3_4.v2_48 or false) ||
      (gio_sys_0_3_4.v2_48 or false);
    gio_sys_0_3_4.v2_48 =
      (f.gio_sys_0_3_4.v2_48 or false) ||
      (f.gio_sys_0_3_4.v2_50 or false) ||
      (gio_sys_0_3_4.v2_50 or false);
    glib_sys_0_3_4.default = true;
    gobject_sys_0_3_4.default = true;
    libc_0_2_42.default = true;
    pkg_config_0_3_12.default = true;
  }) [ bitflags_0_8_2_features glib_sys_0_3_4_features gobject_sys_0_3_4_features libc_0_2_42_features pkg_config_0_3_12_features ];
  glib_0_1_3 = { features?(glib_0_1_3_features {}) }: glib_0_1_3_ {
    dependencies = mapFeatures features ([ bitflags_0_5_0 glib_sys_0_3_4 gobject_sys_0_3_4 lazy_static_0_2_11 libc_0_2_42 ]);
    features = mkFeatures (features.glib_0_1_3 or {});
  };
  glib_0_1_3_features = f: updateFeatures f (rec {
    bitflags_0_5_0.default = true;
    glib_0_1_3.default = (f.glib_0_1_3.default or true);
    glib_0_1_3.v2_38 =
      (f.glib_0_1_3.v2_38 or false) ||
      (f.glib_0_1_3.v2_40 or false) ||
      (glib_0_1_3.v2_40 or false);
    glib_0_1_3.v2_40 =
      (f.glib_0_1_3.v2_40 or false) ||
      (f.glib_0_1_3.v2_44 or false) ||
      (glib_0_1_3.v2_44 or false);
    glib_0_1_3.v2_44 =
      (f.glib_0_1_3.v2_44 or false) ||
      (f.glib_0_1_3.v2_46 or false) ||
      (glib_0_1_3.v2_46 or false);
    glib_0_1_3.v2_46 =
      (f.glib_0_1_3.v2_46 or false) ||
      (f.glib_0_1_3.v2_48 or false) ||
      (glib_0_1_3.v2_48 or false);
    glib_0_1_3.v2_48 =
      (f.glib_0_1_3.v2_48 or false) ||
      (f.glib_0_1_3.v2_50 or false) ||
      (glib_0_1_3.v2_50 or false);
    glib_sys_0_3_4.default = true;
    glib_sys_0_3_4.v2_38 =
      (f.glib_sys_0_3_4.v2_38 or false) ||
      (glib_0_1_3.v2_38 or false) ||
      (f.glib_0_1_3.v2_38 or false);
    glib_sys_0_3_4.v2_40 =
      (f.glib_sys_0_3_4.v2_40 or false) ||
      (glib_0_1_3.v2_40 or false) ||
      (f.glib_0_1_3.v2_40 or false);
    glib_sys_0_3_4.v2_44 =
      (f.glib_sys_0_3_4.v2_44 or false) ||
      (glib_0_1_3.v2_44 or false) ||
      (f.glib_0_1_3.v2_44 or false);
    glib_sys_0_3_4.v2_46 =
      (f.glib_sys_0_3_4.v2_46 or false) ||
      (glib_0_1_3.v2_46 or false) ||
      (f.glib_0_1_3.v2_46 or false);
    glib_sys_0_3_4.v2_48 =
      (f.glib_sys_0_3_4.v2_48 or false) ||
      (glib_0_1_3.v2_48 or false) ||
      (f.glib_0_1_3.v2_48 or false);
    glib_sys_0_3_4.v2_50 =
      (f.glib_sys_0_3_4.v2_50 or false) ||
      (glib_0_1_3.v2_50 or false) ||
      (f.glib_0_1_3.v2_50 or false);
    gobject_sys_0_3_4.default = true;
    gobject_sys_0_3_4.v2_38 =
      (f.gobject_sys_0_3_4.v2_38 or false) ||
      (glib_0_1_3.v2_38 or false) ||
      (f.glib_0_1_3.v2_38 or false);
    gobject_sys_0_3_4.v2_44 =
      (f.gobject_sys_0_3_4.v2_44 or false) ||
      (glib_0_1_3.v2_44 or false) ||
      (f.glib_0_1_3.v2_44 or false);
    gobject_sys_0_3_4.v2_46 =
      (f.gobject_sys_0_3_4.v2_46 or false) ||
      (glib_0_1_3.v2_46 or false) ||
      (f.glib_0_1_3.v2_46 or false);
    lazy_static_0_2_11.default = true;
    libc_0_2_42.default = true;
  }) [ bitflags_0_5_0_features glib_sys_0_3_4_features gobject_sys_0_3_4_features lazy_static_0_2_11_features libc_0_2_42_features ];
  glib_sys_0_3_4 = { features?(glib_sys_0_3_4_features {}) }: glib_sys_0_3_4_ {
    dependencies = mapFeatures features ([ bitflags_0_8_2 libc_0_2_42 ]);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_12 ]);
    features = mkFeatures (features.glib_sys_0_3_4 or {});
  };
  glib_sys_0_3_4_features = f: updateFeatures f (rec {
    bitflags_0_8_2.default = true;
    glib_sys_0_3_4.default = (f.glib_sys_0_3_4.default or true);
    glib_sys_0_3_4.v2_34 =
      (f.glib_sys_0_3_4.v2_34 or false) ||
      (f.glib_sys_0_3_4.v2_36 or false) ||
      (glib_sys_0_3_4.v2_36 or false);
    glib_sys_0_3_4.v2_36 =
      (f.glib_sys_0_3_4.v2_36 or false) ||
      (f.glib_sys_0_3_4.v2_38 or false) ||
      (glib_sys_0_3_4.v2_38 or false);
    glib_sys_0_3_4.v2_38 =
      (f.glib_sys_0_3_4.v2_38 or false) ||
      (f.glib_sys_0_3_4.v2_40 or false) ||
      (glib_sys_0_3_4.v2_40 or false);
    glib_sys_0_3_4.v2_40 =
      (f.glib_sys_0_3_4.v2_40 or false) ||
      (f.glib_sys_0_3_4.v2_44 or false) ||
      (glib_sys_0_3_4.v2_44 or false);
    glib_sys_0_3_4.v2_44 =
      (f.glib_sys_0_3_4.v2_44 or false) ||
      (f.glib_sys_0_3_4.v2_46 or false) ||
      (glib_sys_0_3_4.v2_46 or false);
    glib_sys_0_3_4.v2_46 =
      (f.glib_sys_0_3_4.v2_46 or false) ||
      (f.glib_sys_0_3_4.v2_48 or false) ||
      (glib_sys_0_3_4.v2_48 or false);
    glib_sys_0_3_4.v2_48 =
      (f.glib_sys_0_3_4.v2_48 or false) ||
      (f.glib_sys_0_3_4.v2_50 or false) ||
      (glib_sys_0_3_4.v2_50 or false);
    libc_0_2_42.default = true;
    pkg_config_0_3_12.default = true;
  }) [ bitflags_0_8_2_features libc_0_2_42_features pkg_config_0_3_12_features ];
  gobject_sys_0_3_4 = { features?(gobject_sys_0_3_4_features {}) }: gobject_sys_0_3_4_ {
    dependencies = mapFeatures features ([ bitflags_0_8_2 glib_sys_0_3_4 libc_0_2_42 ]);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_12 ]);
    features = mkFeatures (features.gobject_sys_0_3_4 or {});
  };
  gobject_sys_0_3_4_features = f: updateFeatures f (rec {
    bitflags_0_8_2.default = true;
    glib_sys_0_3_4.default = true;
    gobject_sys_0_3_4.default = (f.gobject_sys_0_3_4.default or true);
    gobject_sys_0_3_4.v2_34 =
      (f.gobject_sys_0_3_4.v2_34 or false) ||
      (f.gobject_sys_0_3_4.v2_36 or false) ||
      (gobject_sys_0_3_4.v2_36 or false);
    gobject_sys_0_3_4.v2_36 =
      (f.gobject_sys_0_3_4.v2_36 or false) ||
      (f.gobject_sys_0_3_4.v2_38 or false) ||
      (gobject_sys_0_3_4.v2_38 or false);
    gobject_sys_0_3_4.v2_38 =
      (f.gobject_sys_0_3_4.v2_38 or false) ||
      (f.gobject_sys_0_3_4.v2_42 or false) ||
      (gobject_sys_0_3_4.v2_42 or false);
    gobject_sys_0_3_4.v2_42 =
      (f.gobject_sys_0_3_4.v2_42 or false) ||
      (f.gobject_sys_0_3_4.v2_44 or false) ||
      (gobject_sys_0_3_4.v2_44 or false);
    gobject_sys_0_3_4.v2_44 =
      (f.gobject_sys_0_3_4.v2_44 or false) ||
      (f.gobject_sys_0_3_4.v2_46 or false) ||
      (gobject_sys_0_3_4.v2_46 or false);
    libc_0_2_42.default = true;
    pkg_config_0_3_12.default = true;
  }) [ bitflags_0_8_2_features glib_sys_0_3_4_features libc_0_2_42_features pkg_config_0_3_12_features ];
  gtk_0_1_3 = { features?(gtk_0_1_3_features {}) }: gtk_0_1_3_ {
    dependencies = mapFeatures features ([ bitflags_0_5_0 cairo_rs_0_1_3 cairo_sys_rs_0_3_4 gdk_0_5_3 gdk_pixbuf_0_1_3 gdk_pixbuf_sys_0_3_4 gdk_sys_0_3_4 gio_0_1_3 gio_sys_0_3_4 glib_0_1_3 glib_sys_0_3_4 gobject_sys_0_3_4 gtk_sys_0_3_4 libc_0_2_42 pango_0_1_3 ]);
    buildDependencies = mapFeatures features ([]);
    features = mkFeatures (features.gtk_0_1_3 or {});
  };
  gtk_0_1_3_features = f: updateFeatures f (rec {
    bitflags_0_5_0.default = true;
    cairo_rs_0_1_3.default = true;
    cairo_sys_rs_0_3_4.default = true;
    gdk_0_5_3.default = true;
    gdk_0_5_3.embed-lgpl-docs =
      (f.gdk_0_5_3.embed-lgpl-docs or false) ||
      (gtk_0_1_3.embed-lgpl-docs or false) ||
      (f.gtk_0_1_3.embed-lgpl-docs or false);
    gdk_0_5_3.purge-lgpl-docs =
      (f.gdk_0_5_3.purge-lgpl-docs or false) ||
      (gtk_0_1_3.purge-lgpl-docs or false) ||
      (f.gtk_0_1_3.purge-lgpl-docs or false);
    gdk_0_5_3.v3_10 =
      (f.gdk_0_5_3.v3_10 or false) ||
      (gtk_0_1_3.v3_10 or false) ||
      (f.gtk_0_1_3.v3_10 or false);
    gdk_0_5_3.v3_12 =
      (f.gdk_0_5_3.v3_12 or false) ||
      (gtk_0_1_3.v3_12 or false) ||
      (f.gtk_0_1_3.v3_12 or false);
    gdk_0_5_3.v3_14 =
      (f.gdk_0_5_3.v3_14 or false) ||
      (gtk_0_1_3.v3_14 or false) ||
      (f.gtk_0_1_3.v3_14 or false);
    gdk_0_5_3.v3_16 =
      (f.gdk_0_5_3.v3_16 or false) ||
      (gtk_0_1_3.v3_16 or false) ||
      (f.gtk_0_1_3.v3_16 or false);
    gdk_0_5_3.v3_18 =
      (f.gdk_0_5_3.v3_18 or false) ||
      (gtk_0_1_3.v3_18 or false) ||
      (f.gtk_0_1_3.v3_18 or false);
    gdk_0_5_3.v3_20 =
      (f.gdk_0_5_3.v3_20 or false) ||
      (gtk_0_1_3.v3_20 or false) ||
      (f.gtk_0_1_3.v3_20 or false);
    gdk_0_5_3.v3_22 =
      (f.gdk_0_5_3.v3_22 or false) ||
      (gtk_0_1_3.v3_22 or false) ||
      (f.gtk_0_1_3.v3_22 or false);
    gdk_0_5_3.v3_6 =
      (f.gdk_0_5_3.v3_6 or false) ||
      (gtk_0_1_3.v3_6 or false) ||
      (f.gtk_0_1_3.v3_6 or false);
    gdk_0_5_3.v3_8 =
      (f.gdk_0_5_3.v3_8 or false) ||
      (gtk_0_1_3.v3_8 or false) ||
      (f.gtk_0_1_3.v3_8 or false);
    gdk_pixbuf_0_1_3.default = true;
    gdk_pixbuf_sys_0_3_4.default = true;
    gdk_sys_0_3_4.default = true;
    gio_0_1_3.default = true;
    gio_sys_0_3_4.default = true;
    glib_0_1_3.default = true;
    glib_sys_0_3_4.default = true;
    gobject_sys_0_3_4.default = true;
    gtk_0_1_3.default = (f.gtk_0_1_3.default or true);
    gtk_0_1_3.gtk-rs-lgpl-docs =
      (f.gtk_0_1_3.gtk-rs-lgpl-docs or false) ||
      (f.gtk_0_1_3.embed-lgpl-docs or false) ||
      (gtk_0_1_3.embed-lgpl-docs or false) ||
      (f.gtk_0_1_3.purge-lgpl-docs or false) ||
      (gtk_0_1_3.purge-lgpl-docs or false);
    gtk_0_1_3.v3_10 =
      (f.gtk_0_1_3.v3_10 or false) ||
      (f.gtk_0_1_3.v3_12 or false) ||
      (gtk_0_1_3.v3_12 or false);
    gtk_0_1_3.v3_12 =
      (f.gtk_0_1_3.v3_12 or false) ||
      (f.gtk_0_1_3.v3_14 or false) ||
      (gtk_0_1_3.v3_14 or false);
    gtk_0_1_3.v3_14 =
      (f.gtk_0_1_3.v3_14 or false) ||
      (f.gtk_0_1_3.v3_16 or false) ||
      (gtk_0_1_3.v3_16 or false);
    gtk_0_1_3.v3_16 =
      (f.gtk_0_1_3.v3_16 or false) ||
      (f.gtk_0_1_3.v3_18 or false) ||
      (gtk_0_1_3.v3_18 or false);
    gtk_0_1_3.v3_18 =
      (f.gtk_0_1_3.v3_18 or false) ||
      (f.gtk_0_1_3.v3_20 or false) ||
      (gtk_0_1_3.v3_20 or false);
    gtk_0_1_3.v3_20 =
      (f.gtk_0_1_3.v3_20 or false) ||
      (f.gtk_0_1_3.v3_22 or false) ||
      (gtk_0_1_3.v3_22 or false);
    gtk_0_1_3.v3_6 =
      (f.gtk_0_1_3.v3_6 or false) ||
      (f.gtk_0_1_3.v3_8 or false) ||
      (gtk_0_1_3.v3_8 or false);
    gtk_0_1_3.v3_8 =
      (f.gtk_0_1_3.v3_8 or false) ||
      (f.gtk_0_1_3.v3_10 or false) ||
      (gtk_0_1_3.v3_10 or false);
    gtk_sys_0_3_4.default = true;
    gtk_sys_0_3_4.v3_10 =
      (f.gtk_sys_0_3_4.v3_10 or false) ||
      (gtk_0_1_3.v3_10 or false) ||
      (f.gtk_0_1_3.v3_10 or false);
    gtk_sys_0_3_4.v3_12 =
      (f.gtk_sys_0_3_4.v3_12 or false) ||
      (gtk_0_1_3.v3_12 or false) ||
      (f.gtk_0_1_3.v3_12 or false);
    gtk_sys_0_3_4.v3_14 =
      (f.gtk_sys_0_3_4.v3_14 or false) ||
      (gtk_0_1_3.v3_14 or false) ||
      (f.gtk_0_1_3.v3_14 or false);
    gtk_sys_0_3_4.v3_16 =
      (f.gtk_sys_0_3_4.v3_16 or false) ||
      (gtk_0_1_3.v3_16 or false) ||
      (f.gtk_0_1_3.v3_16 or false);
    gtk_sys_0_3_4.v3_18 =
      (f.gtk_sys_0_3_4.v3_18 or false) ||
      (gtk_0_1_3.v3_18 or false) ||
      (f.gtk_0_1_3.v3_18 or false);
    gtk_sys_0_3_4.v3_20 =
      (f.gtk_sys_0_3_4.v3_20 or false) ||
      (gtk_0_1_3.v3_20 or false) ||
      (f.gtk_0_1_3.v3_20 or false);
    gtk_sys_0_3_4.v3_22 =
      (f.gtk_sys_0_3_4.v3_22 or false) ||
      (gtk_0_1_3.v3_22 or false) ||
      (f.gtk_0_1_3.v3_22 or false);
    gtk_sys_0_3_4.v3_6 =
      (f.gtk_sys_0_3_4.v3_6 or false) ||
      (gtk_0_1_3.v3_6 or false) ||
      (f.gtk_0_1_3.v3_6 or false);
    gtk_sys_0_3_4.v3_8 =
      (f.gtk_sys_0_3_4.v3_8 or false) ||
      (gtk_0_1_3.v3_8 or false) ||
      (f.gtk_0_1_3.v3_8 or false);
    libc_0_2_42.default = true;
    pango_0_1_3.default = true;
  }) [ bitflags_0_5_0_features cairo_rs_0_1_3_features cairo_sys_rs_0_3_4_features gdk_0_5_3_features gdk_pixbuf_0_1_3_features gdk_pixbuf_sys_0_3_4_features gdk_sys_0_3_4_features gio_0_1_3_features gio_sys_0_3_4_features glib_0_1_3_features glib_sys_0_3_4_features gobject_sys_0_3_4_features gtk_sys_0_3_4_features libc_0_2_42_features pango_0_1_3_features ];
  gtk_sys_0_3_4 = { features?(gtk_sys_0_3_4_features {}) }: gtk_sys_0_3_4_ {
    dependencies = mapFeatures features ([ atk_sys_0_3_4 bitflags_0_8_2 cairo_sys_rs_0_3_4 gdk_pixbuf_sys_0_3_4 gdk_sys_0_3_4 gio_sys_0_3_4 glib_sys_0_3_4 gobject_sys_0_3_4 libc_0_2_42 pango_sys_0_3_4 ]);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_12 ]);
    features = mkFeatures (features.gtk_sys_0_3_4 or {});
  };
  gtk_sys_0_3_4_features = f: updateFeatures f (rec {
    atk_sys_0_3_4.default = true;
    bitflags_0_8_2.default = true;
    cairo_sys_rs_0_3_4.default = true;
    gdk_pixbuf_sys_0_3_4.default = true;
    gdk_sys_0_3_4.default = true;
    gio_sys_0_3_4.default = true;
    glib_sys_0_3_4.default = true;
    gobject_sys_0_3_4.default = true;
    gtk_sys_0_3_4.default = (f.gtk_sys_0_3_4.default or true);
    gtk_sys_0_3_4.v3_10 =
      (f.gtk_sys_0_3_4.v3_10 or false) ||
      (f.gtk_sys_0_3_4.v3_12 or false) ||
      (gtk_sys_0_3_4.v3_12 or false);
    gtk_sys_0_3_4.v3_12 =
      (f.gtk_sys_0_3_4.v3_12 or false) ||
      (f.gtk_sys_0_3_4.v3_14 or false) ||
      (gtk_sys_0_3_4.v3_14 or false);
    gtk_sys_0_3_4.v3_14 =
      (f.gtk_sys_0_3_4.v3_14 or false) ||
      (f.gtk_sys_0_3_4.v3_16 or false) ||
      (gtk_sys_0_3_4.v3_16 or false);
    gtk_sys_0_3_4.v3_16 =
      (f.gtk_sys_0_3_4.v3_16 or false) ||
      (f.gtk_sys_0_3_4.v3_18 or false) ||
      (gtk_sys_0_3_4.v3_18 or false);
    gtk_sys_0_3_4.v3_18 =
      (f.gtk_sys_0_3_4.v3_18 or false) ||
      (f.gtk_sys_0_3_4.v3_20 or false) ||
      (gtk_sys_0_3_4.v3_20 or false);
    gtk_sys_0_3_4.v3_20 =
      (f.gtk_sys_0_3_4.v3_20 or false) ||
      (f.gtk_sys_0_3_4.v3_22 or false) ||
      (gtk_sys_0_3_4.v3_22 or false);
    gtk_sys_0_3_4.v3_6 =
      (f.gtk_sys_0_3_4.v3_6 or false) ||
      (f.gtk_sys_0_3_4.v3_8 or false) ||
      (gtk_sys_0_3_4.v3_8 or false);
    gtk_sys_0_3_4.v3_8 =
      (f.gtk_sys_0_3_4.v3_8 or false) ||
      (f.gtk_sys_0_3_4.v3_10 or false) ||
      (gtk_sys_0_3_4.v3_10 or false);
    libc_0_2_42.default = true;
    pango_sys_0_3_4.default = true;
    pkg_config_0_3_12.default = true;
  }) [ atk_sys_0_3_4_features bitflags_0_8_2_features cairo_sys_rs_0_3_4_features gdk_pixbuf_sys_0_3_4_features gdk_sys_0_3_4_features gio_sys_0_3_4_features glib_sys_0_3_4_features gobject_sys_0_3_4_features libc_0_2_42_features pango_sys_0_3_4_features pkg_config_0_3_12_features ];
  itoa_0_3_4 = { features?(itoa_0_3_4_features {}) }: itoa_0_3_4_ {
    features = mkFeatures (features.itoa_0_3_4 or {});
  };
  itoa_0_3_4_features = f: updateFeatures f (rec {
    itoa_0_3_4.default = (f.itoa_0_3_4.default or true);
  }) [];
  lazy_static_0_2_11 = { features?(lazy_static_0_2_11_features {}) }: lazy_static_0_2_11_ {
    dependencies = mapFeatures features ([]);
    features = mkFeatures (features.lazy_static_0_2_11 or {});
  };
  lazy_static_0_2_11_features = f: updateFeatures f (rec {
    lazy_static_0_2_11.compiletest_rs =
      (f.lazy_static_0_2_11.compiletest_rs or false) ||
      (f.lazy_static_0_2_11.compiletest or false) ||
      (lazy_static_0_2_11.compiletest or false);
    lazy_static_0_2_11.default = (f.lazy_static_0_2_11.default or true);
    lazy_static_0_2_11.nightly =
      (f.lazy_static_0_2_11.nightly or false) ||
      (f.lazy_static_0_2_11.spin_no_std or false) ||
      (lazy_static_0_2_11.spin_no_std or false);
    lazy_static_0_2_11.spin =
      (f.lazy_static_0_2_11.spin or false) ||
      (f.lazy_static_0_2_11.spin_no_std or false) ||
      (lazy_static_0_2_11.spin_no_std or false);
  }) [];
  lazy_static_1_0_2 = { features?(lazy_static_1_0_2_features {}) }: lazy_static_1_0_2_ {
    dependencies = mapFeatures features ([]);
    features = mkFeatures (features.lazy_static_1_0_2 or {});
  };
  lazy_static_1_0_2_features = f: updateFeatures f (rec {
    lazy_static_1_0_2.default = (f.lazy_static_1_0_2.default or true);
    lazy_static_1_0_2.nightly =
      (f.lazy_static_1_0_2.nightly or false) ||
      (f.lazy_static_1_0_2.spin_no_std or false) ||
      (lazy_static_1_0_2.spin_no_std or false);
    lazy_static_1_0_2.spin =
      (f.lazy_static_1_0_2.spin or false) ||
      (f.lazy_static_1_0_2.spin_no_std or false) ||
      (lazy_static_1_0_2.spin_no_std or false);
  }) [];
  libc_0_2_42 = { features?(libc_0_2_42_features {}) }: libc_0_2_42_ {
    features = mkFeatures (features.libc_0_2_42 or {});
  };
  libc_0_2_42_features = f: updateFeatures f (rec {
    libc_0_2_42.default = (f.libc_0_2_42.default or true);
    libc_0_2_42.use_std =
      (f.libc_0_2_42.use_std or false) ||
      (f.libc_0_2_42.default or false) ||
      (libc_0_2_42.default or false);
  }) [];
  log_0_3_9 = { features?(log_0_3_9_features {}) }: log_0_3_9_ {
    dependencies = mapFeatures features ([ log_0_4_3 ]);
    features = mkFeatures (features.log_0_3_9 or {});
  };
  log_0_3_9_features = f: updateFeatures f (rec {
    log_0_3_9.default = (f.log_0_3_9.default or true);
    log_0_3_9.use_std =
      (f.log_0_3_9.use_std or false) ||
      (f.log_0_3_9.default or false) ||
      (log_0_3_9.default or false);
    log_0_4_3.default = true;
    log_0_4_3.max_level_debug =
      (f.log_0_4_3.max_level_debug or false) ||
      (log_0_3_9.max_level_debug or false) ||
      (f.log_0_3_9.max_level_debug or false);
    log_0_4_3.max_level_error =
      (f.log_0_4_3.max_level_error or false) ||
      (log_0_3_9.max_level_error or false) ||
      (f.log_0_3_9.max_level_error or false);
    log_0_4_3.max_level_info =
      (f.log_0_4_3.max_level_info or false) ||
      (log_0_3_9.max_level_info or false) ||
      (f.log_0_3_9.max_level_info or false);
    log_0_4_3.max_level_off =
      (f.log_0_4_3.max_level_off or false) ||
      (log_0_3_9.max_level_off or false) ||
      (f.log_0_3_9.max_level_off or false);
    log_0_4_3.max_level_trace =
      (f.log_0_4_3.max_level_trace or false) ||
      (log_0_3_9.max_level_trace or false) ||
      (f.log_0_3_9.max_level_trace or false);
    log_0_4_3.max_level_warn =
      (f.log_0_4_3.max_level_warn or false) ||
      (log_0_3_9.max_level_warn or false) ||
      (f.log_0_3_9.max_level_warn or false);
    log_0_4_3.release_max_level_debug =
      (f.log_0_4_3.release_max_level_debug or false) ||
      (log_0_3_9.release_max_level_debug or false) ||
      (f.log_0_3_9.release_max_level_debug or false);
    log_0_4_3.release_max_level_error =
      (f.log_0_4_3.release_max_level_error or false) ||
      (log_0_3_9.release_max_level_error or false) ||
      (f.log_0_3_9.release_max_level_error or false);
    log_0_4_3.release_max_level_info =
      (f.log_0_4_3.release_max_level_info or false) ||
      (log_0_3_9.release_max_level_info or false) ||
      (f.log_0_3_9.release_max_level_info or false);
    log_0_4_3.release_max_level_off =
      (f.log_0_4_3.release_max_level_off or false) ||
      (log_0_3_9.release_max_level_off or false) ||
      (f.log_0_3_9.release_max_level_off or false);
    log_0_4_3.release_max_level_trace =
      (f.log_0_4_3.release_max_level_trace or false) ||
      (log_0_3_9.release_max_level_trace or false) ||
      (f.log_0_3_9.release_max_level_trace or false);
    log_0_4_3.release_max_level_warn =
      (f.log_0_4_3.release_max_level_warn or false) ||
      (log_0_3_9.release_max_level_warn or false) ||
      (f.log_0_3_9.release_max_level_warn or false);
    log_0_4_3.std =
      (f.log_0_4_3.std or false) ||
      (log_0_3_9.use_std or false) ||
      (f.log_0_3_9.use_std or false);
  }) [ log_0_4_3_features ];
  log_0_4_3 = { features?(log_0_4_3_features {}) }: log_0_4_3_ {
    dependencies = mapFeatures features ([ cfg_if_0_1_4 ]);
    features = mkFeatures (features.log_0_4_3 or {});
  };
  log_0_4_3_features = f: updateFeatures f (rec {
    cfg_if_0_1_4.default = true;
    log_0_4_3.default = (f.log_0_4_3.default or true);
  }) [ cfg_if_0_1_4_features ];
  memchr_2_0_1 = { features?(memchr_2_0_1_features {}) }: memchr_2_0_1_ {
    dependencies = mapFeatures features ([ ]
      ++ (if features.memchr_2_0_1.libc or false then [ libc_0_2_42 ] else []));
    features = mkFeatures (features.memchr_2_0_1 or {});
  };
  memchr_2_0_1_features = f: updateFeatures f (rec {
    libc_0_2_42.default = (f.libc_0_2_42.default or false);
    libc_0_2_42.use_std =
      (f.libc_0_2_42.use_std or false) ||
      (memchr_2_0_1.use_std or false) ||
      (f.memchr_2_0_1.use_std or false);
    memchr_2_0_1.default = (f.memchr_2_0_1.default or true);
    memchr_2_0_1.libc =
      (f.memchr_2_0_1.libc or false) ||
      (f.memchr_2_0_1.default or false) ||
      (memchr_2_0_1.default or false) ||
      (f.memchr_2_0_1.use_std or false) ||
      (memchr_2_0_1.use_std or false);
    memchr_2_0_1.use_std =
      (f.memchr_2_0_1.use_std or false) ||
      (f.memchr_2_0_1.default or false) ||
      (memchr_2_0_1.default or false);
  }) [ libc_0_2_42_features ];
  num_0_1_42 = { features?(num_0_1_42_features {}) }: num_0_1_42_ {
    dependencies = mapFeatures features ([ num_integer_0_1_39 num_iter_0_1_37 num_traits_0_2_5 ]);
    features = mkFeatures (features.num_0_1_42 or {});
  };
  num_0_1_42_features = f: updateFeatures f (rec {
    num_0_1_42.bigint =
      (f.num_0_1_42.bigint or false) ||
      (f.num_0_1_42.default or false) ||
      (num_0_1_42.default or false);
    num_0_1_42.complex =
      (f.num_0_1_42.complex or false) ||
      (f.num_0_1_42.default or false) ||
      (num_0_1_42.default or false);
    num_0_1_42.default = (f.num_0_1_42.default or true);
    num_0_1_42.num-bigint =
      (f.num_0_1_42.num-bigint or false) ||
      (f.num_0_1_42.bigint or false) ||
      (num_0_1_42.bigint or false);
    num_0_1_42.num-complex =
      (f.num_0_1_42.num-complex or false) ||
      (f.num_0_1_42.complex or false) ||
      (num_0_1_42.complex or false);
    num_0_1_42.num-rational =
      (f.num_0_1_42.num-rational or false) ||
      (f.num_0_1_42.rational or false) ||
      (num_0_1_42.rational or false);
    num_0_1_42.rational =
      (f.num_0_1_42.rational or false) ||
      (f.num_0_1_42.default or false) ||
      (num_0_1_42.default or false);
    num_0_1_42.rustc-serialize =
      (f.num_0_1_42.rustc-serialize or false) ||
      (f.num_0_1_42.default or false) ||
      (num_0_1_42.default or false);
    num_integer_0_1_39.default = true;
    num_iter_0_1_37.default = true;
    num_traits_0_2_5.default = true;
  }) [ num_integer_0_1_39_features num_iter_0_1_37_features num_traits_0_2_5_features ];
  num_integer_0_1_39 = { features?(num_integer_0_1_39_features {}) }: num_integer_0_1_39_ {
    dependencies = mapFeatures features ([ num_traits_0_2_5 ]);
    features = mkFeatures (features.num_integer_0_1_39 or {});
  };
  num_integer_0_1_39_features = f: updateFeatures f (rec {
    num_integer_0_1_39.default = (f.num_integer_0_1_39.default or true);
    num_integer_0_1_39.std =
      (f.num_integer_0_1_39.std or false) ||
      (f.num_integer_0_1_39.default or false) ||
      (num_integer_0_1_39.default or false);
    num_traits_0_2_5.default = (f.num_traits_0_2_5.default or false);
    num_traits_0_2_5.i128 =
      (f.num_traits_0_2_5.i128 or false) ||
      (num_integer_0_1_39.i128 or false) ||
      (f.num_integer_0_1_39.i128 or false);
    num_traits_0_2_5.std =
      (f.num_traits_0_2_5.std or false) ||
      (num_integer_0_1_39.std or false) ||
      (f.num_integer_0_1_39.std or false);
  }) [ num_traits_0_2_5_features ];
  num_iter_0_1_37 = { features?(num_iter_0_1_37_features {}) }: num_iter_0_1_37_ {
    dependencies = mapFeatures features ([ num_integer_0_1_39 num_traits_0_2_5 ]);
    features = mkFeatures (features.num_iter_0_1_37 or {});
  };
  num_iter_0_1_37_features = f: updateFeatures f (rec {
    num_integer_0_1_39.default = (f.num_integer_0_1_39.default or false);
    num_integer_0_1_39.i128 =
      (f.num_integer_0_1_39.i128 or false) ||
      (num_iter_0_1_37.i128 or false) ||
      (f.num_iter_0_1_37.i128 or false);
    num_integer_0_1_39.std =
      (f.num_integer_0_1_39.std or false) ||
      (num_iter_0_1_37.std or false) ||
      (f.num_iter_0_1_37.std or false);
    num_iter_0_1_37.default = (f.num_iter_0_1_37.default or true);
    num_iter_0_1_37.std =
      (f.num_iter_0_1_37.std or false) ||
      (f.num_iter_0_1_37.default or false) ||
      (num_iter_0_1_37.default or false);
    num_traits_0_2_5.default = (f.num_traits_0_2_5.default or false);
    num_traits_0_2_5.i128 =
      (f.num_traits_0_2_5.i128 or false) ||
      (num_iter_0_1_37.i128 or false) ||
      (f.num_iter_0_1_37.i128 or false);
    num_traits_0_2_5.std =
      (f.num_traits_0_2_5.std or false) ||
      (num_iter_0_1_37.std or false) ||
      (f.num_iter_0_1_37.std or false);
  }) [ num_integer_0_1_39_features num_traits_0_2_5_features ];
  num_traits_0_1_43 = { features?(num_traits_0_1_43_features {}) }: num_traits_0_1_43_ {
    dependencies = mapFeatures features ([ num_traits_0_2_5 ]);
  };
  num_traits_0_1_43_features = f: updateFeatures f (rec {
    num_traits_0_1_43.default = (f.num_traits_0_1_43.default or true);
    num_traits_0_2_5.default = true;
  }) [ num_traits_0_2_5_features ];
  num_traits_0_2_5 = { features?(num_traits_0_2_5_features {}) }: num_traits_0_2_5_ {
    features = mkFeatures (features.num_traits_0_2_5 or {});
  };
  num_traits_0_2_5_features = f: updateFeatures f (rec {
    num_traits_0_2_5.default = (f.num_traits_0_2_5.default or true);
    num_traits_0_2_5.std =
      (f.num_traits_0_2_5.std or false) ||
      (f.num_traits_0_2_5.default or false) ||
      (num_traits_0_2_5.default or false);
  }) [];
  pango_0_1_3 = { features?(pango_0_1_3_features {}) }: pango_0_1_3_ {
    dependencies = mapFeatures features ([ bitflags_0_5_0 glib_0_1_3 libc_0_2_42 pango_sys_0_3_4 ]);
    features = mkFeatures (features.pango_0_1_3 or {});
  };
  pango_0_1_3_features = f: updateFeatures f (rec {
    bitflags_0_5_0.default = true;
    glib_0_1_3.default = true;
    libc_0_2_42.default = true;
    pango_0_1_3.default = (f.pango_0_1_3.default or true);
    pango_0_1_3.v1_31 =
      (f.pango_0_1_3.v1_31 or false) ||
      (f.pango_0_1_3.v1_32 or false) ||
      (pango_0_1_3.v1_32 or false);
    pango_0_1_3.v1_32 =
      (f.pango_0_1_3.v1_32 or false) ||
      (f.pango_0_1_3.v1_32_4 or false) ||
      (pango_0_1_3.v1_32_4 or false);
    pango_0_1_3.v1_32_4 =
      (f.pango_0_1_3.v1_32_4 or false) ||
      (f.pango_0_1_3.v1_34 or false) ||
      (pango_0_1_3.v1_34 or false);
    pango_0_1_3.v1_34 =
      (f.pango_0_1_3.v1_34 or false) ||
      (f.pango_0_1_3.v1_36_7 or false) ||
      (pango_0_1_3.v1_36_7 or false);
    pango_0_1_3.v1_36_7 =
      (f.pango_0_1_3.v1_36_7 or false) ||
      (f.pango_0_1_3.v1_38 or false) ||
      (pango_0_1_3.v1_38 or false);
    pango_0_1_3.v1_38 =
      (f.pango_0_1_3.v1_38 or false) ||
      (f.pango_0_1_3.v1_42 or false) ||
      (pango_0_1_3.v1_42 or false);
    pango_sys_0_3_4.default = true;
    pango_sys_0_3_4.v1_31 =
      (f.pango_sys_0_3_4.v1_31 or false) ||
      (pango_0_1_3.v1_31 or false) ||
      (f.pango_0_1_3.v1_31 or false);
    pango_sys_0_3_4.v1_32 =
      (f.pango_sys_0_3_4.v1_32 or false) ||
      (pango_0_1_3.v1_32 or false) ||
      (f.pango_0_1_3.v1_32 or false);
    pango_sys_0_3_4.v1_32_4 =
      (f.pango_sys_0_3_4.v1_32_4 or false) ||
      (pango_0_1_3.v1_32_4 or false) ||
      (f.pango_0_1_3.v1_32_4 or false);
    pango_sys_0_3_4.v1_34 =
      (f.pango_sys_0_3_4.v1_34 or false) ||
      (pango_0_1_3.v1_34 or false) ||
      (f.pango_0_1_3.v1_34 or false);
    pango_sys_0_3_4.v1_36_7 =
      (f.pango_sys_0_3_4.v1_36_7 or false) ||
      (pango_0_1_3.v1_36_7 or false) ||
      (f.pango_0_1_3.v1_36_7 or false);
    pango_sys_0_3_4.v1_38 =
      (f.pango_sys_0_3_4.v1_38 or false) ||
      (pango_0_1_3.v1_38 or false) ||
      (f.pango_0_1_3.v1_38 or false);
    pango_sys_0_3_4.v1_42 =
      (f.pango_sys_0_3_4.v1_42 or false) ||
      (pango_0_1_3.v1_42 or false) ||
      (f.pango_0_1_3.v1_42 or false);
  }) [ bitflags_0_5_0_features glib_0_1_3_features libc_0_2_42_features pango_sys_0_3_4_features ];
  pango_sys_0_3_4 = { features?(pango_sys_0_3_4_features {}) }: pango_sys_0_3_4_ {
    dependencies = mapFeatures features ([ bitflags_0_8_2 glib_sys_0_3_4 gobject_sys_0_3_4 libc_0_2_42 ]);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_12 ]);
    features = mkFeatures (features.pango_sys_0_3_4 or {});
  };
  pango_sys_0_3_4_features = f: updateFeatures f (rec {
    bitflags_0_8_2.default = true;
    glib_sys_0_3_4.default = true;
    gobject_sys_0_3_4.default = true;
    libc_0_2_42.default = true;
    pango_sys_0_3_4.default = (f.pango_sys_0_3_4.default or true);
    pango_sys_0_3_4.v1_31 =
      (f.pango_sys_0_3_4.v1_31 or false) ||
      (f.pango_sys_0_3_4.v1_32 or false) ||
      (pango_sys_0_3_4.v1_32 or false);
    pango_sys_0_3_4.v1_32 =
      (f.pango_sys_0_3_4.v1_32 or false) ||
      (f.pango_sys_0_3_4.v1_32_4 or false) ||
      (pango_sys_0_3_4.v1_32_4 or false);
    pango_sys_0_3_4.v1_32_4 =
      (f.pango_sys_0_3_4.v1_32_4 or false) ||
      (f.pango_sys_0_3_4.v1_34 or false) ||
      (pango_sys_0_3_4.v1_34 or false);
    pango_sys_0_3_4.v1_34 =
      (f.pango_sys_0_3_4.v1_34 or false) ||
      (f.pango_sys_0_3_4.v1_36_7 or false) ||
      (pango_sys_0_3_4.v1_36_7 or false);
    pango_sys_0_3_4.v1_36_7 =
      (f.pango_sys_0_3_4.v1_36_7 or false) ||
      (f.pango_sys_0_3_4.v1_38 or false) ||
      (pango_sys_0_3_4.v1_38 or false);
    pango_sys_0_3_4.v1_38 =
      (f.pango_sys_0_3_4.v1_38 or false) ||
      (f.pango_sys_0_3_4.v1_42 or false) ||
      (pango_sys_0_3_4.v1_42 or false);
    pkg_config_0_3_12.default = true;
  }) [ bitflags_0_8_2_features glib_sys_0_3_4_features gobject_sys_0_3_4_features libc_0_2_42_features pkg_config_0_3_12_features ];
  pkg_config_0_3_12 = { features?(pkg_config_0_3_12_features {}) }: pkg_config_0_3_12_ {};
  pkg_config_0_3_12_features = f: updateFeatures f (rec {
    pkg_config_0_3_12.default = (f.pkg_config_0_3_12.default or true);
  }) [];
  quote_0_3_15 = { features?(quote_0_3_15_features {}) }: quote_0_3_15_ {};
  quote_0_3_15_features = f: updateFeatures f (rec {
    quote_0_3_15.default = (f.quote_0_3_15.default or true);
  }) [];
  redox_syscall_0_1_40 = { features?(redox_syscall_0_1_40_features {}) }: redox_syscall_0_1_40_ {};
  redox_syscall_0_1_40_features = f: updateFeatures f (rec {
    redox_syscall_0_1_40.default = (f.redox_syscall_0_1_40.default or true);
  }) [];
  regex_0_2_11 = { features?(regex_0_2_11_features {}) }: regex_0_2_11_ {
    dependencies = mapFeatures features ([ aho_corasick_0_6_6 memchr_2_0_1 regex_syntax_0_5_6 thread_local_0_3_5 utf8_ranges_1_0_0 ]);
    features = mkFeatures (features.regex_0_2_11 or {});
  };
  regex_0_2_11_features = f: updateFeatures f (rec {
    aho_corasick_0_6_6.default = true;
    memchr_2_0_1.default = true;
    regex_0_2_11.default = (f.regex_0_2_11.default or true);
    regex_0_2_11.pattern =
      (f.regex_0_2_11.pattern or false) ||
      (f.regex_0_2_11.unstable or false) ||
      (regex_0_2_11.unstable or false);
    regex_syntax_0_5_6.default = true;
    thread_local_0_3_5.default = true;
    utf8_ranges_1_0_0.default = true;
  }) [ aho_corasick_0_6_6_features memchr_2_0_1_features regex_syntax_0_5_6_features thread_local_0_3_5_features utf8_ranges_1_0_0_features ];
  regex_syntax_0_5_6 = { features?(regex_syntax_0_5_6_features {}) }: regex_syntax_0_5_6_ {
    dependencies = mapFeatures features ([ ucd_util_0_1_1 ]);
  };
  regex_syntax_0_5_6_features = f: updateFeatures f (rec {
    regex_syntax_0_5_6.default = (f.regex_syntax_0_5_6.default or true);
    ucd_util_0_1_1.default = true;
  }) [ ucd_util_0_1_1_features ];
  serde_0_9_15 = { features?(serde_0_9_15_features {}) }: serde_0_9_15_ {
    dependencies = mapFeatures features ([]);
    features = mkFeatures (features.serde_0_9_15 or {});
  };
  serde_0_9_15_features = f: updateFeatures f (rec {
    serde_0_9_15.alloc =
      (f.serde_0_9_15.alloc or false) ||
      (f.serde_0_9_15.collections or false) ||
      (serde_0_9_15.collections or false);
    serde_0_9_15.default = (f.serde_0_9_15.default or true);
    serde_0_9_15.serde_derive =
      (f.serde_0_9_15.serde_derive or false) ||
      (f.serde_0_9_15.derive or false) ||
      (serde_0_9_15.derive or false) ||
      (f.serde_0_9_15.playground or false) ||
      (serde_0_9_15.playground or false);
    serde_0_9_15.std =
      (f.serde_0_9_15.std or false) ||
      (f.serde_0_9_15.default or false) ||
      (serde_0_9_15.default or false) ||
      (f.serde_0_9_15.unstable-testing or false) ||
      (serde_0_9_15.unstable-testing or false);
    serde_0_9_15.unstable =
      (f.serde_0_9_15.unstable or false) ||
      (f.serde_0_9_15.alloc or false) ||
      (serde_0_9_15.alloc or false) ||
      (f.serde_0_9_15.unstable-testing or false) ||
      (serde_0_9_15.unstable-testing or false);
  }) [];
  serde_codegen_internals_0_14_2 = { features?(serde_codegen_internals_0_14_2_features {}) }: serde_codegen_internals_0_14_2_ {
    dependencies = mapFeatures features ([ syn_0_11_11 ]);
  };
  serde_codegen_internals_0_14_2_features = f: updateFeatures f (rec {
    serde_codegen_internals_0_14_2.default = (f.serde_codegen_internals_0_14_2.default or true);
    syn_0_11_11.default = (f.syn_0_11_11.default or false);
    syn_0_11_11.parsing = true;
  }) [ syn_0_11_11_features ];
  serde_derive_0_9_15 = { features?(serde_derive_0_9_15_features {}) }: serde_derive_0_9_15_ {
    dependencies = mapFeatures features ([ quote_0_3_15 serde_codegen_internals_0_14_2 syn_0_11_11 ]);
    features = mkFeatures (features.serde_derive_0_9_15 or {});
  };
  serde_derive_0_9_15_features = f: updateFeatures f (rec {
    quote_0_3_15.default = true;
    serde_codegen_internals_0_14_2.default = (f.serde_codegen_internals_0_14_2.default or false);
    serde_derive_0_9_15.default = (f.serde_derive_0_9_15.default or true);
    syn_0_11_11.default = true;
    syn_0_11_11.visit = true;
  }) [ quote_0_3_15_features serde_codegen_internals_0_14_2_features syn_0_11_11_features ];
  serde_json_0_9_10 = { features?(serde_json_0_9_10_features {}) }: serde_json_0_9_10_ {
    dependencies = mapFeatures features ([ dtoa_0_4_3 itoa_0_3_4 num_traits_0_1_43 serde_0_9_15 ]);
    features = mkFeatures (features.serde_json_0_9_10 or {});
  };
  serde_json_0_9_10_features = f: updateFeatures f (rec {
    dtoa_0_4_3.default = true;
    itoa_0_3_4.default = true;
    num_traits_0_1_43.default = true;
    serde_0_9_15.default = true;
    serde_json_0_9_10.default = (f.serde_json_0_9_10.default or true);
    serde_json_0_9_10.linked-hash-map =
      (f.serde_json_0_9_10.linked-hash-map or false) ||
      (f.serde_json_0_9_10.preserve_order or false) ||
      (serde_json_0_9_10.preserve_order or false);
  }) [ dtoa_0_4_3_features itoa_0_3_4_features num_traits_0_1_43_features serde_0_9_15_features ];
  syn_0_11_11 = { features?(syn_0_11_11_features {}) }: syn_0_11_11_ {
    dependencies = mapFeatures features ([ ]
      ++ (if features.syn_0_11_11.quote or false then [ quote_0_3_15 ] else [])
      ++ (if features.syn_0_11_11.synom or false then [ synom_0_11_3 ] else [])
      ++ (if features.syn_0_11_11.unicode-xid or false then [ unicode_xid_0_0_4 ] else []));
    features = mkFeatures (features.syn_0_11_11 or {});
  };
  syn_0_11_11_features = f: updateFeatures f (rec {
    quote_0_3_15.default = true;
    syn_0_11_11.default = (f.syn_0_11_11.default or true);
    syn_0_11_11.parsing =
      (f.syn_0_11_11.parsing or false) ||
      (f.syn_0_11_11.default or false) ||
      (syn_0_11_11.default or false);
    syn_0_11_11.printing =
      (f.syn_0_11_11.printing or false) ||
      (f.syn_0_11_11.default or false) ||
      (syn_0_11_11.default or false);
    syn_0_11_11.quote =
      (f.syn_0_11_11.quote or false) ||
      (f.syn_0_11_11.printing or false) ||
      (syn_0_11_11.printing or false);
    syn_0_11_11.synom =
      (f.syn_0_11_11.synom or false) ||
      (f.syn_0_11_11.parsing or false) ||
      (syn_0_11_11.parsing or false);
    syn_0_11_11.unicode-xid =
      (f.syn_0_11_11.unicode-xid or false) ||
      (f.syn_0_11_11.parsing or false) ||
      (syn_0_11_11.parsing or false);
    synom_0_11_3.default = true;
    unicode_xid_0_0_4.default = true;
  }) [ quote_0_3_15_features synom_0_11_3_features unicode_xid_0_0_4_features ];
  synom_0_11_3 = { features?(synom_0_11_3_features {}) }: synom_0_11_3_ {
    dependencies = mapFeatures features ([ unicode_xid_0_0_4 ]);
  };
  synom_0_11_3_features = f: updateFeatures f (rec {
    synom_0_11_3.default = (f.synom_0_11_3.default or true);
    unicode_xid_0_0_4.default = true;
  }) [ unicode_xid_0_0_4_features ];
  task_hookrs_0_3_0 = { features?(task_hookrs_0_3_0_features {}) }: task_hookrs_0_3_0_ {
    dependencies = mapFeatures features ([ chrono_0_2_25 log_0_3_9 serde_0_9_15 serde_derive_0_9_15 serde_json_0_9_10 uuid_0_4_0 ]);
  };
  task_hookrs_0_3_0_features = f: updateFeatures f (rec {
    chrono_0_2_25.default = true;
    log_0_3_9.default = true;
    serde_0_9_15.default = true;
    serde_derive_0_9_15.default = true;
    serde_json_0_9_10.default = true;
    task_hookrs_0_3_0.default = (f.task_hookrs_0_3_0.default or true);
    uuid_0_4_0.default = true;
    uuid_0_4_0.serde = true;
  }) [ chrono_0_2_25_features log_0_3_9_features serde_0_9_15_features serde_derive_0_9_15_features serde_json_0_9_10_features uuid_0_4_0_features ];
  tasktree_0_1_0 = { features?(tasktree_0_1_0_features {}) }: tasktree_0_1_0_ {
    dependencies = mapFeatures features ([ gdk_0_5_3 glib_0_1_3 gtk_0_1_3 lazy_static_0_2_11 regex_0_2_11 serde_0_9_15 serde_derive_0_9_15 serde_json_0_9_10 task_hookrs_0_3_0 uuid_0_4_0 ]);
    features = mkFeatures (features.tasktree_0_1_0 or {});
  };
  tasktree_0_1_0_features = f: updateFeatures f (rec {
    gdk_0_5_3.default = (f.gdk_0_5_3.default or false);
    glib_0_1_3.default = (f.glib_0_1_3.default or false);
    gtk_0_1_3.default = (f.gtk_0_1_3.default or false);
    gtk_0_1_3.v3_18 = true;
    lazy_static_0_2_11.default = true;
    regex_0_2_11.default = true;
    serde_0_9_15.default = true;
    serde_derive_0_9_15.default = true;
    serde_json_0_9_10.default = true;
    task_hookrs_0_3_0.default = true;
    tasktree_0_1_0.default = (f.tasktree_0_1_0.default or true);
    tasktree_0_1_0.set_project =
      (f.tasktree_0_1_0.set_project or false) ||
      (f.tasktree_0_1_0.default or false) ||
      (tasktree_0_1_0.default or false);
    tasktree_0_1_0.set_project_tag =
      (f.tasktree_0_1_0.set_project_tag or false) ||
      (f.tasktree_0_1_0.default or false) ||
      (tasktree_0_1_0.default or false);
    uuid_0_4_0.default = true;
    uuid_0_4_0.serde = true;
  }) [ gdk_0_5_3_features glib_0_1_3_features gtk_0_1_3_features lazy_static_0_2_11_features regex_0_2_11_features serde_0_9_15_features serde_derive_0_9_15_features serde_json_0_9_10_features task_hookrs_0_3_0_features uuid_0_4_0_features ];
  thread_local_0_3_5 = { features?(thread_local_0_3_5_features {}) }: thread_local_0_3_5_ {
    dependencies = mapFeatures features ([ lazy_static_1_0_2 unreachable_1_0_0 ]);
  };
  thread_local_0_3_5_features = f: updateFeatures f (rec {
    lazy_static_1_0_2.default = true;
    thread_local_0_3_5.default = (f.thread_local_0_3_5.default or true);
    unreachable_1_0_0.default = true;
  }) [ lazy_static_1_0_2_features unreachable_1_0_0_features ];
  time_0_1_40 = { features?(time_0_1_40_features {}) }: time_0_1_40_ {
    dependencies = mapFeatures features ([ libc_0_2_42 ])
      ++ (if kernel == "redox" then mapFeatures features ([ redox_syscall_0_1_40 ]) else [])
      ++ (if kernel == "windows" then mapFeatures features ([ winapi_0_3_5 ]) else []);
  };
  time_0_1_40_features = f: updateFeatures f (rec {
    libc_0_2_42.default = true;
    redox_syscall_0_1_40.default = true;
    time_0_1_40.default = (f.time_0_1_40.default or true);
    winapi_0_3_5.default = true;
    winapi_0_3_5.minwinbase = true;
    winapi_0_3_5.minwindef = true;
    winapi_0_3_5.ntdef = true;
    winapi_0_3_5.profileapi = true;
    winapi_0_3_5.std = true;
    winapi_0_3_5.sysinfoapi = true;
    winapi_0_3_5.timezoneapi = true;
  }) [ libc_0_2_42_features redox_syscall_0_1_40_features winapi_0_3_5_features ];
  ucd_util_0_1_1 = { features?(ucd_util_0_1_1_features {}) }: ucd_util_0_1_1_ {};
  ucd_util_0_1_1_features = f: updateFeatures f (rec {
    ucd_util_0_1_1.default = (f.ucd_util_0_1_1.default or true);
  }) [];
  unicode_xid_0_0_4 = { features?(unicode_xid_0_0_4_features {}) }: unicode_xid_0_0_4_ {
    features = mkFeatures (features.unicode_xid_0_0_4 or {});
  };
  unicode_xid_0_0_4_features = f: updateFeatures f (rec {
    unicode_xid_0_0_4.default = (f.unicode_xid_0_0_4.default or true);
  }) [];
  unreachable_1_0_0 = { features?(unreachable_1_0_0_features {}) }: unreachable_1_0_0_ {
    dependencies = mapFeatures features ([ void_1_0_2 ]);
  };
  unreachable_1_0_0_features = f: updateFeatures f (rec {
    unreachable_1_0_0.default = (f.unreachable_1_0_0.default or true);
    void_1_0_2.default = (f.void_1_0_2.default or false);
  }) [ void_1_0_2_features ];
  utf8_ranges_1_0_0 = { features?(utf8_ranges_1_0_0_features {}) }: utf8_ranges_1_0_0_ {};
  utf8_ranges_1_0_0_features = f: updateFeatures f (rec {
    utf8_ranges_1_0_0.default = (f.utf8_ranges_1_0_0.default or true);
  }) [];
  uuid_0_4_0 = { features?(uuid_0_4_0_features {}) }: uuid_0_4_0_ {
    dependencies = mapFeatures features ([ ]
      ++ (if features.uuid_0_4_0.serde or false then [ serde_0_9_15 ] else []));
    features = mkFeatures (features.uuid_0_4_0 or {});
  };
  uuid_0_4_0_features = f: updateFeatures f (rec {
    serde_0_9_15.default = true;
    uuid_0_4_0.default = (f.uuid_0_4_0.default or true);
    uuid_0_4_0.rand =
      (f.uuid_0_4_0.rand or false) ||
      (f.uuid_0_4_0.v4 or false) ||
      (uuid_0_4_0.v4 or false);
    uuid_0_4_0.sha1 =
      (f.uuid_0_4_0.sha1 or false) ||
      (f.uuid_0_4_0.v5 or false) ||
      (uuid_0_4_0.v5 or false);
  }) [ serde_0_9_15_features ];
  void_1_0_2 = { features?(void_1_0_2_features {}) }: void_1_0_2_ {
    features = mkFeatures (features.void_1_0_2 or {});
  };
  void_1_0_2_features = f: updateFeatures f (rec {
    void_1_0_2.default = (f.void_1_0_2.default or true);
    void_1_0_2.std =
      (f.void_1_0_2.std or false) ||
      (f.void_1_0_2.default or false) ||
      (void_1_0_2.default or false);
  }) [];
  winapi_0_2_8 = { features?(winapi_0_2_8_features {}) }: winapi_0_2_8_ {};
  winapi_0_2_8_features = f: updateFeatures f (rec {
    winapi_0_2_8.default = (f.winapi_0_2_8.default or true);
  }) [];
  winapi_0_3_5 = { features?(winapi_0_3_5_features {}) }: winapi_0_3_5_ {
    dependencies = (if kernel == "i686-pc-windows-gnu" then mapFeatures features ([ winapi_i686_pc_windows_gnu_0_4_0 ]) else [])
      ++ (if kernel == "x86_64-pc-windows-gnu" then mapFeatures features ([ winapi_x86_64_pc_windows_gnu_0_4_0 ]) else []);
    features = mkFeatures (features.winapi_0_3_5 or {});
  };
  winapi_0_3_5_features = f: updateFeatures f (rec {
    winapi_0_3_5.default = (f.winapi_0_3_5.default or true);
    winapi_i686_pc_windows_gnu_0_4_0.default = true;
    winapi_x86_64_pc_windows_gnu_0_4_0.default = true;
  }) [ winapi_i686_pc_windows_gnu_0_4_0_features winapi_x86_64_pc_windows_gnu_0_4_0_features ];
  winapi_i686_pc_windows_gnu_0_4_0 = { features?(winapi_i686_pc_windows_gnu_0_4_0_features {}) }: winapi_i686_pc_windows_gnu_0_4_0_ {};
  winapi_i686_pc_windows_gnu_0_4_0_features = f: updateFeatures f (rec {
    winapi_i686_pc_windows_gnu_0_4_0.default = (f.winapi_i686_pc_windows_gnu_0_4_0.default or true);
  }) [];
  winapi_x86_64_pc_windows_gnu_0_4_0 = { features?(winapi_x86_64_pc_windows_gnu_0_4_0_features {}) }: winapi_x86_64_pc_windows_gnu_0_4_0_ {};
  winapi_x86_64_pc_windows_gnu_0_4_0_features = f: updateFeatures f (rec {
    winapi_x86_64_pc_windows_gnu_0_4_0.default = (f.winapi_x86_64_pc_windows_gnu_0_4_0.default or true);
  }) [];
}
