# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];

  fileSystems."/" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/43AC-25F1";
      fsType = "vfat";
    };

  fileSystems."/disk" =
    { device = "/dev/disk/by-uuid/573176bd-8420-4174-a39c-0387c1ee1ac8";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."crypted-nixos".device = "/dev/disk/by-uuid/ceb2366c-099a-4ad1-b9b0-1bfa84189a6e";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/573176bd-8420-4174-a39c-0387c1ee1ac8";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
