theme = "slick"
icons = "awesome"

[[block]]
block = "speedtest"
bytes = false
interval = 1800

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"
chip = "*-isa-*"

[[block]]
block = "net"
device = "wlp61s0"
ssid = true
ip = true
speed_up = true
speed_down = true
graph_up = true
graph_down = true
interval = 5

[[block]]
block = "net"
device = "enp0s31f6"
ssid = true
ip = true
speed_up = true
speed_down = true
graph_up = true
graph_down = true
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "load"
interval = 5
format = "{1m}"
