name: Update flake
on:
  schedule:
    - cron: '0 4 * * *' # Everyday at 04:00 https://crontab.guru/#0_4_*_*_*
run-name: Update flake

jobs:
  flake-update:
    runs-on: nix
    steps:
      - name: Set HOME
        run: echo "HOME=$(dirname $(pwd))" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
