name: Update flake
on:
   #schedule:
   # - cron: '2 * * * *' # Everyday at 04:00 https://crontab.guru/#0_4_*_*_*
run-name: Update flake

jobs:
  flake-update:
    runs-on: nix
    steps:
      - name: Set HOME
        run: echo "HOME=$(dirname $(pwd))" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Configure git
        run: |
            git config user.email "mail@maralorn.de"
            git config user.name "maralorn"
      - name: Update flake.lock
        #run: nix flake update --commit-lock-file
        run: |
            echo "foo" > flake.lock
            git commit -am "flake.lock"
      - name: Create merge request
        run: |
            git checkout -B update-flake
            git push -f origin update-flake
            git push origin HEAD:refs/for/main -o topic=update-flake
