{
 "title": "Accounting",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "Ausgaben & Einnahmen Übersicht Laufendes Jahr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Ausgabenkategorien",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "suffix:€" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT amount, replace(replace(account,'Erfolgskonten:Ausgaben:',''),':',' -> ') as metric, date as time from balances WHERE account SIMILAR TO 'Erfolgskonten:Ausgaben:[^:]*' ORDER BY date;"
    }
   ]
  },
  {
   "title": "Einnahmenkategorien",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "suffix:€" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT -amount, replace(replace(account,'Erfolgskonten:Einnahmen:',''),':',' -> ') as metric, date as time from balances WHERE account SIMILAR TO 'Erfolgskonten:Einnahmen:[^:]*' ORDER BY date;"
    }
   ]
  },
  { "title": "Konten", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Verteilung",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "suffix:€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT amount, replace(replace(account,'Aktiva:Konten:',''),':',' -> ') as metric, date as time from flat_balances WHERE account SIMILAR TO 'Aktiva:Konten:%' ORDER BY date;"
    }
   ]
  },
  {
   "title": "Zeitverlauf",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "suffix:€" } },
   "targets": [
    {
     "rawSql": "SELECT date as time, account as metric, amount FROM flat_balances WHERE account LIKE 'Aktiva:Konten:%' ORDER BY time"
    },
    {
     "rawSql": "SELECT date as time, account as metric, amount FROM balances WHERE account LIKE 'Aktiva' ORDER BY time"
    }
   ]
  },
  {
   "title": "Ausgaben",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "suffix:€" } },
   "targets": [
    {
     "rawSql": "SELECT date as time, replace(account,'Erfolgskonten:Ausgaben:','') as metric, amount FROM flat_balances WHERE account LIKE 'Erfolgskonten:Ausgaben:%' ORDER BY time"
    }
   ]
  },
  {
   "title": "Einnahmen",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "suffix:€" } },
   "targets": [
    {
     "rawSql": "SELECT date as time, replace(account,'Erfolgskonten:Einnahmen:','') as metric, -amount FROM flat_balances WHERE account LIKE 'Erfolgskonten:Einnahmen:%' ORDER BY time"
    }
   ]
  },
  {
   "title": "Diskrepanzen",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "suffix:€" } },
   "targets": [
    {
     "rawSql": "SELECT date as time, account as metric, amount FROM flat_balances WHERE account LIKE 'Aktiva:Umbuchung' OR account LIKE 'Aktiva:Saldokorrektur:%' ORDER BY time"
    }
   ]
  }
 ]
}