name: Nix build
on: [push]
run-name: Test and build flake
jobs:
  nix-build:
    runs-on: nix
    strategy:
       matrix:
         attribute:
           - nixosConfigurations.zeus.config.system.build.toplevel
           - nixosConfigurations.apollo.config.system.build.toplevel
           - nixosConfigurations.hera.config.system.build.toplevel
           - nixosConfigurations.fluffy.config.system.build.toplevel
           - homeModes.zeus
           - homeModes.apollo
    env:
        HOME: .
    steps:
      - uses: actions/checkout@v3
      - run: nix build --builders $(builders-configurator fluffy) --log-format raw .${{ matrix.attribute }} -v
      - run: archive-nix-path
  nix-flake-check:
    runs-on: nix
    env:
        HOME: .
    steps:
      - uses: actions/checkout@v3
      - run: nix flake check --builders $(builders-configurator fluffy) --log-format raw -v
