platform: template
name: ${macsuffix}_bme280_dew_point
lambda: |-
  return (243.5*(log(id(bme280_humidity).state/100)+((17.67*id(bme280_temperature).state)/
  (243.5+id(bme280_temperature).state)))/(17.67-log(id(bme280_humidity).state/100)-
  ((17.67*id(bme280_temperature).state)/(243.5+id(bme280_temperature).state))));
unit_of_measurement: °C
icon: 'mdi:thermometer-alert'
