[package]
name = "rust-scripts"
version = "0.1.0"

[dependencies]
dialog = { git = "https://git.darmstadt.ccc.de/maralorn/dialog-rs.git" }
task-hookrs = { git = "https://git.darmstadt.ccc.de/maralorn/task-hookrs.git"}
lazy_static = "1.0.0"
uuid = "0.6"
chrono = "0.4.2"
error-chain = "0.11.0"
serde_derive = "1.0"
serde = "1.0"
serde_yaml = "0.7"
maildir = "0.1.1"
mailparse = "0.5.1"
regex = "0.2"
serde_json = "1.0"
reqwest = "0.8"
config = "0.9.0"
