[package]
name = "rust-scripts"
version = "0.1.0"
authors = ["Malte Brandy <malte.brandy@maralorn.de>"]

[dependencies]
#task-hookrs = { git = "https://github.com/maralorn/task-hookrs.git", branch = "preview"}
task-hookrs = { path = "/home/maralorn/code/task-hookrs"}
dialog = { path = "/home/maralorn/code/dialog-rs" }
lazy_static = "1.0.0"
uuid = "0.6"
chrono = "0.4.2"
error-chain = "0.11.0"
serde_derive = "1.0"
serde = "1.0"
serde_yaml = "0.7"
maildir = "0.1.1"
mailparse = "0.5.1"
regex = "0.2"
