# Generated by carnix 0.6.6: carnix -o carnix.nix Cargo.lock
{ lib, buildPlatform, buildRustCrate, fetchgit }:
let kernel = buildPlatform.parsed.kernel.name;
    abi = buildPlatform.parsed.abi.name;
    include = includedFiles: src: builtins.filterSource (path: type:
      lib.lists.any (f:
        let p = toString (src + ("/" + f)); in
        (path == p) || (type == "directory" && lib.strings.hasPrefix path p)
      ) includedFiles
    ) src;
    updateFeatures = f: up: functions: builtins.deepSeq f (lib.lists.foldl' (features: fun: fun features) (lib.attrsets.recursiveUpdate f up) functions);
    mapFeatures = features: map (fun: fun { features = features; });
    mkFeatures = feat: lib.lists.foldl (features: featureName:
      if feat.${featureName} or false then
        [ featureName ] ++ features
      else
        features
    ) [] (builtins.attrNames feat);
in
rec {
  rust_scripts = f: rust_scripts_0_1_0 { features = rust_scripts_0_1_0_features { rust_scripts_0_1_0 = f; }; };
  backtrace_0_3_7_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "backtrace";
    version = "0.3.7";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" "The Rust Project Developers" ];
    sha256 = "00zzcgacv516dlhxkrdw4c8vsx3bwkkdrrzi5pnxrhpd87ambjwn";
    inherit dependencies buildDependencies features;
  };
  backtrace_sys_0_1_16_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "backtrace-sys";
    version = "0.1.16";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "1cn2c8q3dn06crmnk0p62czkngam4l8nf57wy33nz1y5g25pszwy";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  bitflags_0_4_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "bitflags";
    version = "0.4.0";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0an03kibhfcc0mcxf6a0mvbab0s7cggnvflw8jn0b15i351h828c";
    inherit dependencies buildDependencies features;
  };
  bitflags_1_0_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "bitflags";
    version = "1.0.3";
    authors = [ "The Rust Project Developers" ];
    sha256 = "162p4w4h1ad76awq6b5yivmls3d50m9cl27d8g588lsps6g8s5rw";
    inherit dependencies buildDependencies features;
  };
  cc_1_0_15_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "cc";
    version = "1.0.15";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "1zmcv4zf888byhay2qakqlc9b8snhy5ccfs35zb6flywmlj8f2c0";
    inherit dependencies buildDependencies features;
  };
  cfg_if_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "cfg-if";
    version = "0.1.3";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "0hphfz5qg40gr5p18gmgy2rzkqj019lii3n0dy3s0a6lnl9106k6";
    inherit dependencies buildDependencies features;
  };
  chrono_0_4_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "chrono";
    version = "0.4.2";
    authors = [ "Kang Seonghoon <public+rust@mearie.org>" "Brandon W Maister <quodlibetor@gmail.com>" ];
    sha256 = "1zp63v1g56kfjnazmqg8s4gb66l0ra8ggn3gzqbf9sr8d5lnfzak";
    inherit dependencies buildDependencies features;
  };
  derive_builder_0_5_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "derive_builder";
    version = "0.5.1";
    authors = [ "Colin Kiegel <kiegel@gmx.de>" "Pascal Hertleif <killercup@gmail.com>" "Jan-Erik Rediger <janerik@fnordig.de>" "Ted Driggs <ted.driggs@outlook.com>" ];
    sha256 = "0w4k4k5g4lfrhzzzqxi9zp4x8m889kg0z36wvbxi9xxgcfy3az8n";
    procMacro = true;
    build = "build/mod.rs";
    inherit dependencies buildDependencies features;
  };
  derive_builder_core_0_2_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "derive_builder_core";
    version = "0.2.0";
    authors = [ "Colin Kiegel <kiegel@gmx.de>" "Pascal Hertleif <killercup@gmail.com>" "Jan-Erik Rediger <janerik@fnordig.de>" "Ted Driggs <ted.driggs@outlook.com>" ];
    sha256 = "14kggzaggy6ra7q88cilyriy3ji4bin5favq6qd1z9vl9nvafgs9";
    inherit dependencies buildDependencies features;
  };
  dialog_0_1_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "dialog";
    version = "0.1.0";
    authors = [ "Malte Brandy <malte.brandy@maralorn.de>" ];
    src = /home/maralorn/code/dialog-rs;
    inherit dependencies buildDependencies features;
  };
  dtoa_0_4_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "dtoa";
    version = "0.4.2";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "1bxsh6fags7nr36vlz07ik2a1rzyipc8x1y30kjk832hf2pzadmw";
    inherit dependencies buildDependencies features;
  };
  encode_unicode_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "encode_unicode";
    version = "0.1.3";
    authors = [ "Torbjørn Birch Moltu <t.b.moltu@lyse.net>" ];
    sha256 = "1avvnhi4cy8vj0j0yjqpwxjz0kbjk3nx5k82rq70nr0fsa4ag73f";
    inherit dependencies buildDependencies features;
  };
  error_chain_0_11_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "error-chain";
    version = "0.11.0";
    authors = [ "Brian Anderson <banderson@mozilla.com>" "Paul Colomiets <paul@colomiets.name>" "Colin Kiegel <kiegel@gmx.de>" "Yamakaky <yamakaky@yamaworld.fr>" ];
    sha256 = "19nz17q6dzp0mx2jhh9qbj45gkvvgcl7zq9z2ai5a8ihbisfj6d7";
    inherit dependencies buildDependencies features;
  };
  fuchsia_zircon_0_3_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "fuchsia-zircon";
    version = "0.3.3";
    authors = [ "Raph Levien <raph@google.com>" ];
    sha256 = "0jrf4shb1699r4la8z358vri8318w4mdi6qzfqy30p2ymjlca4gk";
    inherit dependencies buildDependencies features;
  };
  fuchsia_zircon_sys_0_3_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "fuchsia-zircon-sys";
    version = "0.3.3";
    authors = [ "Raph Levien <raph@google.com>" ];
    sha256 = "08jp1zxrm9jbrr6l26bjal4dbm8bxfy57ickdgibsqxr1n9j3hf5";
    inherit dependencies buildDependencies features;
  };
  iso8601_0_2_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "iso8601";
    version = "0.2.0";
    authors = [ "Jan-Erik Rediger <janerik@fnordig.de>" "Hendrik Sollich <hendrik@hoodie.de>" ];
    sha256 = "18zm5pnc26q1q8l65r702bcnvkdzzbdmsq96gxcwa00lxja7l2d4";
    inherit dependencies buildDependencies features;
  };
  itoa_0_4_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "itoa";
    version = "0.4.1";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "1jyrsmrm5q4r2ipmq5hvvkqg0mgnlbk44lm7gr0v9ymvbrh2gbij";
    inherit dependencies buildDependencies features;
  };
  kairos_0_1_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "kairos";
    version = "0.1.0";
    authors = [ "Matthias Beyer <mail@beyermatthias.de>" ];
    sha256 = "06q5gn83c85jf4d7kf8sp1xd94cqfp2ri2kb3zsm5n4865wsbkjr";
    inherit dependencies buildDependencies features;
  };
  kernel32_sys_0_2_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "kernel32-sys";
    version = "0.2.2";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "1lrw1hbinyvr6cp28g60z97w32w8vsk6pahk64pmrv2fmby8srfj";
    libName = "kernel32";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  lazy_static_1_0_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "lazy_static";
    version = "1.0.0";
    authors = [ "Marvin Löbel <loebel.marvin@gmail.com>" ];
    sha256 = "0wfvqyr2nvx2mbsrscg5y7gfa9skhb8p72ayanl8vl49pw24v4fh";
    inherit dependencies buildDependencies features;
  };
  libc_0_2_40_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "libc";
    version = "0.2.40";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1xfc39237ldzgr8x8wcflgdr8zssi3wif7g2zxc02d94gzkjsw83";
    inherit dependencies buildDependencies features;
  };
  linked_hash_map_0_5_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "linked-hash-map";
    version = "0.5.1";
    authors = [ "Stepan Koltsov <stepan.koltsov@gmail.com>" "Andrew Paseltiner <apaseltiner@gmail.com>" ];
    sha256 = "1f29c7j53z7w5v0g115yii9dmmbsahr93ak375g48vi75v3p4030";
    inherit dependencies buildDependencies features;
  };
  log_0_4_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "log";
    version = "0.4.1";
    authors = [ "The Rust Project Developers" ];
    sha256 = "01vm8yy3wngvyj6qp1x3xpcb4xq7v67yn9l7fsma8kz28mliz90d";
    inherit dependencies buildDependencies features;
  };
  memchr_1_0_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "memchr";
    version = "1.0.2";
    authors = [ "Andrew Gallant <jamslam@gmail.com>" "bluss" ];
    sha256 = "0dfb8ifl9nrc9kzgd5z91q6qg87sh285q1ih7xgrsglmqfav9lg7";
    inherit dependencies buildDependencies features;
  };
  nix_0_5_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "nix";
    version = "0.5.1";
    authors = [ "Carl Lerche <me@carllerche.com>" ];
    sha256 = "17dp0x440bl6a4dc3rxqnj7p2sx46isg2hhvdqpjkdlca84qd7b2";
    inherit dependencies buildDependencies features;
  };
  nom_3_2_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "nom";
    version = "3.2.1";
    authors = [ "contact@geoffroycouprie.com" ];
    sha256 = "1vcllxrz9hdw6j25kn020ka3psz1vkaqh1hm3yfak2240zrxgi07";
    inherit dependencies buildDependencies features;
  };
  num_integer_0_1_38_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "num-integer";
    version = "0.1.38";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0xcyvsg43zrmaanf546l67mz816g5jigxi8818rx5y95xid722yy";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  num_traits_0_2_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "num-traits";
    version = "0.2.4";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0j0n4lcxbqq8q9v2qcyybz6aqxvmghzl5q2p19ds0c8fl5wviqmj";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  proc_macro2_0_3_8_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "proc-macro2";
    version = "0.3.8";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "0ixnavxcd6sk1861hjgnfxly7qgq4ch1iplsx0nclvjjkwg39qdc";
    inherit dependencies buildDependencies features;
  };
  quote_0_3_15_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "quote";
    version = "0.3.15";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "09il61jv4kd1360spaj46qwyl21fv1qz18fsv2jra8wdnlgl5jsg";
    inherit dependencies buildDependencies features;
  };
  quote_0_5_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "quote";
    version = "0.5.2";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "062cnp12j09x0z0nj4j5pfh26h35zlrks07asxgqhfhcym1ba595";
    inherit dependencies buildDependencies features;
  };
  rand_0_4_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "rand";
    version = "0.4.2";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0h8pkg23wb67i8904sm76iyr1jlmhklb85vbpz9c9191a24xzkfm";
    inherit dependencies buildDependencies features;
  };
  redox_syscall_0_1_37_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "redox_syscall";
    version = "0.1.37";
    authors = [ "Jeremy Soller <jackpot51@gmail.com>" ];
    sha256 = "0qa0jl9cr3qp80an8vshp2mcn8rzvwiavs1398hq1vsjw7pc3h2v";
    libName = "syscall";
    inherit dependencies buildDependencies features;
  };
  rust_scripts_0_1_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "rust-scripts";
    version = "0.1.0";
    authors = [ "Malte Brandy <malte.brandy@maralorn.de>" ];
    src = ./.;
    inherit dependencies buildDependencies features;
  };
  rustc_demangle_0_1_8_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "rustc-demangle";
    version = "0.1.8";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "0xn5l86qfwngmdsjbglj30wh37zplvch96jl9raysl3k06gkkv3c";
    inherit dependencies buildDependencies features;
  };
  rustyline_1_0_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "rustyline";
    version = "1.0.0";
    authors = [ "Katsu Kawakami <kkawa1570@gmail.com>" ];
    sha256 = "0xq3xal9wdyf0z46maspr0qsvw84n2ip8146n433ywvn1c03zwg9";
    inherit dependencies buildDependencies features;
  };
  serde_1_0_55_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "serde";
    version = "1.0.55";
    authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "1vpslfs3j8xbl3srmzppa34h0908q0sj4hyrmlrpklhldii5vbqh";
    inherit dependencies buildDependencies features;
  };
  serde_derive_1_0_55_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "serde_derive";
    version = "1.0.55";
    authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "1ggcidzgi51l3lsdf8gg46ivn61py8rnrf6garpcxwmdbfcc8lgk";
    procMacro = true;
    inherit dependencies buildDependencies features;
  };
  serde_json_1_0_17_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "serde_json";
    version = "1.0.17";
    authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "1q4660h8yqq5y3wkpqfzwmyvncfb2z7qqxblngs4jfi1sndi2zlz";
    inherit dependencies buildDependencies features;
  };
  serde_yaml_0_7_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "serde_yaml";
    version = "0.7.4";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "03zcqcr643i4knpkhs250d60yvildhcmcsc6s9gxmkax5khc8qwg";
    inherit dependencies buildDependencies features;
  };
  syn_0_11_11_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "syn";
    version = "0.11.11";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "0yw8ng7x1dn5a6ykg0ib49y7r9nhzgpiq2989rqdp7rdz3n85502";
    inherit dependencies buildDependencies features;
  };
  syn_0_13_10_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "syn";
    version = "0.13.10";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "0dbvdxlpvx7f8iw5cbv88vbyszp72df8y8zhl36gj73g1xwdqfhx";
    inherit dependencies buildDependencies features;
  };
  synom_0_11_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "synom";
    version = "0.11.3";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "1l6d1s9qjfp6ng2s2z8219igvlv7gyk8gby97sdykqc1r93d8rhc";
    inherit dependencies buildDependencies features;
  };
  task_hookrs_0_5_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "task-hookrs";
    version = "0.5.0";
    authors = [ "Matthias Beyer <mail@beyermatthias.de>" "Mario Krehl <mario-krehl@gmx.de>" "Malte Brandy <malte.brandy@maralorn.de>" ];
    src = /home/maralorn/code/task-hookrs;
    inherit dependencies buildDependencies features;
  };
  termios_0_3_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "termios";
    version = "0.3.0";
    authors = [ "David Cuddeback <david.cuddeback@gmail.com>" ];
    sha256 = "0d5vpwdaimbq2pz4a4njcyxc2spvssxn2v8n9mc6flys4h0ir9nv";
    inherit dependencies buildDependencies features;
  };
  time_0_1_40_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "time";
    version = "0.1.40";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0wgnbjamljz6bqxsd5axc4p2mmhkqfrryj4gf2yswjaxiw5dd01m";
    inherit dependencies buildDependencies features;
  };
  unicode_width_0_1_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "unicode-width";
    version = "0.1.4";
    authors = [ "kwantam <kwantam@gmail.com>" ];
    sha256 = "1rp7a04icn9y5c0lm74nrd4py0rdl0af8bhdwq7g478n1xifpifl";
    inherit dependencies buildDependencies features;
  };
  unicode_xid_0_0_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "unicode-xid";
    version = "0.0.4";
    authors = [ "erick.tryzelaar <erick.tryzelaar@gmail.com>" "kwantam <kwantam@gmail.com>" ];
    sha256 = "1dc8wkkcd3s6534s5aw4lbjn8m67flkkbnajp5bl8408wdg8rh9v";
    inherit dependencies buildDependencies features;
  };
  unicode_xid_0_1_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "unicode-xid";
    version = "0.1.0";
    authors = [ "erick.tryzelaar <erick.tryzelaar@gmail.com>" "kwantam <kwantam@gmail.com>" ];
    sha256 = "05wdmwlfzxhq3nhsxn6wx4q8dhxzzfb9szsz6wiw092m1rjj01zj";
    inherit dependencies buildDependencies features;
  };
  uuid_0_6_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "uuid";
    version = "0.6.3";
    authors = [ "Ashley Mannix<ashleymannix@live.com.au>" "Christopher Armstrong" "Dylan DPC<dylan.dpc@gmail.com>" "Hunar Roop Kahlon<hunar.roop@gmail.com>" ];
    sha256 = "1kjp5xglhab4saaikn95zn3mr4zja7484pv307cb5bxm2sawb8p6";
    inherit dependencies buildDependencies features;
  };
  winapi_0_2_8_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi";
    version = "0.2.8";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "0a45b58ywf12vb7gvj6h3j264nydynmzyqz8d8rqxsj6icqv82as";
    inherit dependencies buildDependencies features;
  };
  winapi_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi";
    version = "0.3.4";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "1qbrf5dcnd8j36cawby5d9r5vx07r0l4ryf672pfncnp8895k9lx";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  winapi_build_0_1_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi-build";
    version = "0.1.1";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "1lxlpi87rkhxcwp2ykf1ldw3p108hwm24nywf3jfrvmff4rjhqga";
    libName = "build";
    inherit dependencies buildDependencies features;
  };
  winapi_i686_pc_windows_gnu_0_4_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi-i686-pc-windows-gnu";
    version = "0.4.0";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "05ihkij18r4gamjpxj4gra24514can762imjzlmak5wlzidplzrp";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  winapi_x86_64_pc_windows_gnu_0_4_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi-x86_64-pc-windows-gnu";
    version = "0.4.0";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "0n1ylmlsb8yg1v583i4xy0qmqg42275flvbc51hdqjjfjcl9vlbj";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  yaml_rust_0_4_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "yaml-rust";
    version = "0.4.0";
    authors = [ "Yuheng Chen <yuhengchen@sensetime.com>" ];
    sha256 = "1mqv1jagn9hfym28ypp2dq6hw9kcyilzil9ydlpls0ivb8d9i3h8";
    inherit dependencies buildDependencies features;
  };
  backtrace_0_3_7 = { features?(backtrace_0_3_7_features {}) }: backtrace_0_3_7_ {
    dependencies = mapFeatures features ([ cfg_if_0_1_3 rustc_demangle_0_1_8 ])
      ++ (if (kernel == "linux" || kernel == "darwin") && !(kernel == "fuchsia") && !(kernel == "emscripten") && !(kernel == "darwin") && !(kernel == "ios") then mapFeatures features ([ ]
      ++ (if features.backtrace_0_3_7.backtrace-sys or false then [ backtrace_sys_0_1_16 ] else [])) else [])
      ++ (if (kernel == "linux" || kernel == "darwin") then mapFeatures features ([ libc_0_2_40 ]) else [])
      ++ (if kernel == "windows" then mapFeatures features ([ ]
      ++ (if features.backtrace_0_3_7.winapi or false then [ winapi_0_3_4 ] else [])) else []);
    features = mkFeatures (features.backtrace_0_3_7 or {});
  };
  backtrace_0_3_7_features = f: updateFeatures f (rec {
    backtrace_0_3_7.addr2line =
      (f.backtrace_0_3_7.addr2line or false) ||
      (f.backtrace_0_3_7.gimli-symbolize or false) ||
      (backtrace_0_3_7.gimli-symbolize or false);
    backtrace_0_3_7.backtrace-sys =
      (f.backtrace_0_3_7.backtrace-sys or false) ||
      (f.backtrace_0_3_7.libbacktrace or false) ||
      (backtrace_0_3_7.libbacktrace or false);
    backtrace_0_3_7.coresymbolication =
      (f.backtrace_0_3_7.coresymbolication or false) ||
      (f.backtrace_0_3_7.default or false) ||
      (backtrace_0_3_7.default or false);
    backtrace_0_3_7.dbghelp =
      (f.backtrace_0_3_7.dbghelp or false) ||
      (f.backtrace_0_3_7.default or false) ||
      (backtrace_0_3_7.default or false);
    backtrace_0_3_7.default = (f.backtrace_0_3_7.default or true);
    backtrace_0_3_7.dladdr =
      (f.backtrace_0_3_7.dladdr or false) ||
      (f.backtrace_0_3_7.default or false) ||
      (backtrace_0_3_7.default or false);
    backtrace_0_3_7.findshlibs =
      (f.backtrace_0_3_7.findshlibs or false) ||
      (f.backtrace_0_3_7.gimli-symbolize or false) ||
      (backtrace_0_3_7.gimli-symbolize or false);
    backtrace_0_3_7.gimli =
      (f.backtrace_0_3_7.gimli or false) ||
      (f.backtrace_0_3_7.gimli-symbolize or false) ||
      (backtrace_0_3_7.gimli-symbolize or false);
    backtrace_0_3_7.libbacktrace =
      (f.backtrace_0_3_7.libbacktrace or false) ||
      (f.backtrace_0_3_7.default or false) ||
      (backtrace_0_3_7.default or false);
    backtrace_0_3_7.libunwind =
      (f.backtrace_0_3_7.libunwind or false) ||
      (f.backtrace_0_3_7.default or false) ||
      (backtrace_0_3_7.default or false);
    backtrace_0_3_7.memmap =
      (f.backtrace_0_3_7.memmap or false) ||
      (f.backtrace_0_3_7.gimli-symbolize or false) ||
      (backtrace_0_3_7.gimli-symbolize or false);
    backtrace_0_3_7.object =
      (f.backtrace_0_3_7.object or false) ||
      (f.backtrace_0_3_7.gimli-symbolize or false) ||
      (backtrace_0_3_7.gimli-symbolize or false);
    backtrace_0_3_7.rustc-serialize =
      (f.backtrace_0_3_7.rustc-serialize or false) ||
      (f.backtrace_0_3_7.serialize-rustc or false) ||
      (backtrace_0_3_7.serialize-rustc or false);
    backtrace_0_3_7.serde =
      (f.backtrace_0_3_7.serde or false) ||
      (f.backtrace_0_3_7.serialize-serde or false) ||
      (backtrace_0_3_7.serialize-serde or false);
    backtrace_0_3_7.serde_derive =
      (f.backtrace_0_3_7.serde_derive or false) ||
      (f.backtrace_0_3_7.serialize-serde or false) ||
      (backtrace_0_3_7.serialize-serde or false);
    backtrace_0_3_7.winapi =
      (f.backtrace_0_3_7.winapi or false) ||
      (f.backtrace_0_3_7.dbghelp or false) ||
      (backtrace_0_3_7.dbghelp or false);
    backtrace_sys_0_1_16.default = true;
    cfg_if_0_1_3.default = true;
    libc_0_2_40.default = true;
    rustc_demangle_0_1_8.default = true;
    winapi_0_3_4.dbghelp = true;
    winapi_0_3_4.default = true;
    winapi_0_3_4.minwindef = true;
    winapi_0_3_4.processthreadsapi = true;
    winapi_0_3_4.std = true;
    winapi_0_3_4.winnt = true;
  }) [ cfg_if_0_1_3_features rustc_demangle_0_1_8_features backtrace_sys_0_1_16_features libc_0_2_40_features winapi_0_3_4_features ];
  backtrace_sys_0_1_16 = { features?(backtrace_sys_0_1_16_features {}) }: backtrace_sys_0_1_16_ {
    dependencies = mapFeatures features ([ libc_0_2_40 ]);
    buildDependencies = mapFeatures features ([ cc_1_0_15 ]);
  };
  backtrace_sys_0_1_16_features = f: updateFeatures f (rec {
    backtrace_sys_0_1_16.default = (f.backtrace_sys_0_1_16.default or true);
    cc_1_0_15.default = true;
    libc_0_2_40.default = true;
  }) [ libc_0_2_40_features cc_1_0_15_features ];
  bitflags_0_4_0 = { features?(bitflags_0_4_0_features {}) }: bitflags_0_4_0_ {
    features = mkFeatures (features.bitflags_0_4_0 or {});
  };
  bitflags_0_4_0_features = f: updateFeatures f (rec {
    bitflags_0_4_0.default = (f.bitflags_0_4_0.default or true);
  }) [];
  bitflags_1_0_3 = { features?(bitflags_1_0_3_features {}) }: bitflags_1_0_3_ {
    features = mkFeatures (features.bitflags_1_0_3 or {});
  };
  bitflags_1_0_3_features = f: updateFeatures f (rec {
    bitflags_1_0_3.default = (f.bitflags_1_0_3.default or true);
  }) [];
  cc_1_0_15 = { features?(cc_1_0_15_features {}) }: cc_1_0_15_ {
    dependencies = mapFeatures features ([]);
    features = mkFeatures (features.cc_1_0_15 or {});
  };
  cc_1_0_15_features = f: updateFeatures f (rec {
    cc_1_0_15.default = (f.cc_1_0_15.default or true);
    cc_1_0_15.rayon =
      (f.cc_1_0_15.rayon or false) ||
      (f.cc_1_0_15.parallel or false) ||
      (cc_1_0_15.parallel or false);
  }) [];
  cfg_if_0_1_3 = { features?(cfg_if_0_1_3_features {}) }: cfg_if_0_1_3_ {};
  cfg_if_0_1_3_features = f: updateFeatures f (rec {
    cfg_if_0_1_3.default = (f.cfg_if_0_1_3.default or true);
  }) [];
  chrono_0_4_2 = { features?(chrono_0_4_2_features {}) }: chrono_0_4_2_ {
    dependencies = mapFeatures features ([ num_integer_0_1_38 num_traits_0_2_4 ]
      ++ (if features.chrono_0_4_2.time or false then [ time_0_1_40 ] else []));
    features = mkFeatures (features.chrono_0_4_2 or {});
  };
  chrono_0_4_2_features = f: updateFeatures f (rec {
    chrono_0_4_2.clock =
      (f.chrono_0_4_2.clock or false) ||
      (f.chrono_0_4_2.default or false) ||
      (chrono_0_4_2.default or false);
    chrono_0_4_2.default = (f.chrono_0_4_2.default or true);
    chrono_0_4_2.time =
      (f.chrono_0_4_2.time or false) ||
      (f.chrono_0_4_2.clock or false) ||
      (chrono_0_4_2.clock or false);
    num_integer_0_1_38.default = (f.num_integer_0_1_38.default or false);
    num_traits_0_2_4.default = (f.num_traits_0_2_4.default or false);
    time_0_1_40.default = true;
  }) [ num_integer_0_1_38_features num_traits_0_2_4_features time_0_1_40_features ];
  derive_builder_0_5_1 = { features?(derive_builder_0_5_1_features {}) }: derive_builder_0_5_1_ {
    dependencies = mapFeatures features ([ derive_builder_core_0_2_0 quote_0_3_15 syn_0_11_11 ]);
    buildDependencies = mapFeatures features ([]);
    features = mkFeatures (features.derive_builder_0_5_1 or {});
  };
  derive_builder_0_5_1_features = f: updateFeatures f (rec {
    derive_builder_0_5_1.compiletest_rs =
      (f.derive_builder_0_5_1.compiletest_rs or false) ||
      (f.derive_builder_0_5_1.nightlytests or false) ||
      (derive_builder_0_5_1.nightlytests or false);
    derive_builder_0_5_1.default = (f.derive_builder_0_5_1.default or true);
    derive_builder_0_5_1.env_logger =
      (f.derive_builder_0_5_1.env_logger or false) ||
      (f.derive_builder_0_5_1.logging or false) ||
      (derive_builder_0_5_1.logging or false);
    derive_builder_0_5_1.log =
      (f.derive_builder_0_5_1.log or false) ||
      (f.derive_builder_0_5_1.logging or false) ||
      (derive_builder_0_5_1.logging or false);
    derive_builder_0_5_1.skeptic =
      (f.derive_builder_0_5_1.skeptic or false) ||
      (f.derive_builder_0_5_1.skeptic_tests or false) ||
      (derive_builder_0_5_1.skeptic_tests or false);
    derive_builder_core_0_2_0.default = true;
    derive_builder_core_0_2_0.logging =
      (f.derive_builder_core_0_2_0.logging or false) ||
      (derive_builder_0_5_1.logging or false) ||
      (f.derive_builder_0_5_1.logging or false);
    quote_0_3_15.default = true;
    syn_0_11_11.default = true;
  }) [ derive_builder_core_0_2_0_features quote_0_3_15_features syn_0_11_11_features ];
  derive_builder_core_0_2_0 = { features?(derive_builder_core_0_2_0_features {}) }: derive_builder_core_0_2_0_ {
    dependencies = mapFeatures features ([ quote_0_3_15 syn_0_11_11 ]);
    features = mkFeatures (features.derive_builder_core_0_2_0 or {});
  };
  derive_builder_core_0_2_0_features = f: updateFeatures f (rec {
    derive_builder_core_0_2_0.default = (f.derive_builder_core_0_2_0.default or true);
    derive_builder_core_0_2_0.log =
      (f.derive_builder_core_0_2_0.log or false) ||
      (f.derive_builder_core_0_2_0.logging or false) ||
      (derive_builder_core_0_2_0.logging or false);
    quote_0_3_15.default = true;
    syn_0_11_11.default = true;
  }) [ quote_0_3_15_features syn_0_11_11_features ];
  dialog_0_1_0 = { features?(dialog_0_1_0_features {}) }: dialog_0_1_0_ {
    dependencies = mapFeatures features ([ error_chain_0_11_0 rustyline_1_0_0 termios_0_3_0 ]);
  };
  dialog_0_1_0_features = f: updateFeatures f (rec {
    dialog_0_1_0.default = (f.dialog_0_1_0.default or true);
    error_chain_0_11_0.default = true;
    rustyline_1_0_0.default = true;
    termios_0_3_0.default = true;
  }) [ error_chain_0_11_0_features rustyline_1_0_0_features termios_0_3_0_features ];
  dtoa_0_4_2 = { features?(dtoa_0_4_2_features {}) }: dtoa_0_4_2_ {};
  dtoa_0_4_2_features = f: updateFeatures f (rec {
    dtoa_0_4_2.default = (f.dtoa_0_4_2.default or true);
  }) [];
  encode_unicode_0_1_3 = { features?(encode_unicode_0_1_3_features {}) }: encode_unicode_0_1_3_ {
    dependencies = mapFeatures features ([]);
  };
  encode_unicode_0_1_3_features = f: updateFeatures f (rec {
    encode_unicode_0_1_3.default = (f.encode_unicode_0_1_3.default or true);
  }) [];
  error_chain_0_11_0 = { features?(error_chain_0_11_0_features {}) }: error_chain_0_11_0_ {
    dependencies = mapFeatures features ([ ]
      ++ (if features.error_chain_0_11_0.backtrace or false then [ backtrace_0_3_7 ] else []));
    features = mkFeatures (features.error_chain_0_11_0 or {});
  };
  error_chain_0_11_0_features = f: updateFeatures f (rec {
    backtrace_0_3_7.default = true;
    error_chain_0_11_0.backtrace =
      (f.error_chain_0_11_0.backtrace or false) ||
      (f.error_chain_0_11_0.default or false) ||
      (error_chain_0_11_0.default or false);
    error_chain_0_11_0.default = (f.error_chain_0_11_0.default or true);
    error_chain_0_11_0.example_generated =
      (f.error_chain_0_11_0.example_generated or false) ||
      (f.error_chain_0_11_0.default or false) ||
      (error_chain_0_11_0.default or false);
  }) [ backtrace_0_3_7_features ];
  fuchsia_zircon_0_3_3 = { features?(fuchsia_zircon_0_3_3_features {}) }: fuchsia_zircon_0_3_3_ {
    dependencies = mapFeatures features ([ bitflags_1_0_3 fuchsia_zircon_sys_0_3_3 ]);
  };
  fuchsia_zircon_0_3_3_features = f: updateFeatures f (rec {
    bitflags_1_0_3.default = true;
    fuchsia_zircon_0_3_3.default = (f.fuchsia_zircon_0_3_3.default or true);
    fuchsia_zircon_sys_0_3_3.default = true;
  }) [ bitflags_1_0_3_features fuchsia_zircon_sys_0_3_3_features ];
  fuchsia_zircon_sys_0_3_3 = { features?(fuchsia_zircon_sys_0_3_3_features {}) }: fuchsia_zircon_sys_0_3_3_ {};
  fuchsia_zircon_sys_0_3_3_features = f: updateFeatures f (rec {
    fuchsia_zircon_sys_0_3_3.default = (f.fuchsia_zircon_sys_0_3_3.default or true);
  }) [];
  iso8601_0_2_0 = { features?(iso8601_0_2_0_features {}) }: iso8601_0_2_0_ {
    dependencies = mapFeatures features ([ nom_3_2_1 ]);
  };
  iso8601_0_2_0_features = f: updateFeatures f (rec {
    iso8601_0_2_0.default = (f.iso8601_0_2_0.default or true);
    nom_3_2_1.default = true;
  }) [ nom_3_2_1_features ];
  itoa_0_4_1 = { features?(itoa_0_4_1_features {}) }: itoa_0_4_1_ {
    features = mkFeatures (features.itoa_0_4_1 or {});
  };
  itoa_0_4_1_features = f: updateFeatures f (rec {
    itoa_0_4_1.default = (f.itoa_0_4_1.default or true);
    itoa_0_4_1.std =
      (f.itoa_0_4_1.std or false) ||
      (f.itoa_0_4_1.default or false) ||
      (itoa_0_4_1.default or false);
  }) [];
  kairos_0_1_0 = { features?(kairos_0_1_0_features {}) }: kairos_0_1_0_ {
    dependencies = mapFeatures features ([ chrono_0_4_2 error_chain_0_11_0 iso8601_0_2_0 nom_3_2_1 ]);
    features = mkFeatures (features.kairos_0_1_0 or {});
  };
  kairos_0_1_0_features = f: updateFeatures f (rec {
    chrono_0_4_2.default = true;
    error_chain_0_11_0.default = true;
    iso8601_0_2_0.default = true;
    kairos_0_1_0.default = (f.kairos_0_1_0.default or true);
    kairos_0_1_0.filters =
      (f.kairos_0_1_0.filters or false) ||
      (f.kairos_0_1_0.with-filters or false) ||
      (kairos_0_1_0.with-filters or false);
    nom_3_2_1.default = true;
  }) [ chrono_0_4_2_features error_chain_0_11_0_features iso8601_0_2_0_features nom_3_2_1_features ];
  kernel32_sys_0_2_2 = { features?(kernel32_sys_0_2_2_features {}) }: kernel32_sys_0_2_2_ {
    dependencies = mapFeatures features ([ winapi_0_2_8 ]);
    buildDependencies = mapFeatures features ([ winapi_build_0_1_1 ]);
  };
  kernel32_sys_0_2_2_features = f: updateFeatures f (rec {
    kernel32_sys_0_2_2.default = (f.kernel32_sys_0_2_2.default or true);
    winapi_0_2_8.default = true;
    winapi_build_0_1_1.default = true;
  }) [ winapi_0_2_8_features winapi_build_0_1_1_features ];
  lazy_static_1_0_0 = { features?(lazy_static_1_0_0_features {}) }: lazy_static_1_0_0_ {
    dependencies = mapFeatures features ([]);
    features = mkFeatures (features.lazy_static_1_0_0 or {});
  };
  lazy_static_1_0_0_features = f: updateFeatures f (rec {
    lazy_static_1_0_0.compiletest_rs =
      (f.lazy_static_1_0_0.compiletest_rs or false) ||
      (f.lazy_static_1_0_0.compiletest or false) ||
      (lazy_static_1_0_0.compiletest or false);
    lazy_static_1_0_0.default = (f.lazy_static_1_0_0.default or true);
    lazy_static_1_0_0.nightly =
      (f.lazy_static_1_0_0.nightly or false) ||
      (f.lazy_static_1_0_0.spin_no_std or false) ||
      (lazy_static_1_0_0.spin_no_std or false);
    lazy_static_1_0_0.spin =
      (f.lazy_static_1_0_0.spin or false) ||
      (f.lazy_static_1_0_0.spin_no_std or false) ||
      (lazy_static_1_0_0.spin_no_std or false);
  }) [];
  libc_0_2_40 = { features?(libc_0_2_40_features {}) }: libc_0_2_40_ {
    features = mkFeatures (features.libc_0_2_40 or {});
  };
  libc_0_2_40_features = f: updateFeatures f (rec {
    libc_0_2_40.default = (f.libc_0_2_40.default or true);
    libc_0_2_40.use_std =
      (f.libc_0_2_40.use_std or false) ||
      (f.libc_0_2_40.default or false) ||
      (libc_0_2_40.default or false);
  }) [];
  linked_hash_map_0_5_1 = { features?(linked_hash_map_0_5_1_features {}) }: linked_hash_map_0_5_1_ {
    dependencies = mapFeatures features ([]);
    features = mkFeatures (features.linked_hash_map_0_5_1 or {});
  };
  linked_hash_map_0_5_1_features = f: updateFeatures f (rec {
    linked_hash_map_0_5_1.default = (f.linked_hash_map_0_5_1.default or true);
    linked_hash_map_0_5_1.heapsize =
      (f.linked_hash_map_0_5_1.heapsize or false) ||
      (f.linked_hash_map_0_5_1.heapsize_impl or false) ||
      (linked_hash_map_0_5_1.heapsize_impl or false);
    linked_hash_map_0_5_1.serde =
      (f.linked_hash_map_0_5_1.serde or false) ||
      (f.linked_hash_map_0_5_1.serde_impl or false) ||
      (linked_hash_map_0_5_1.serde_impl or false);
    linked_hash_map_0_5_1.serde_test =
      (f.linked_hash_map_0_5_1.serde_test or false) ||
      (f.linked_hash_map_0_5_1.serde_impl or false) ||
      (linked_hash_map_0_5_1.serde_impl or false);
  }) [];
  log_0_4_1 = { features?(log_0_4_1_features {}) }: log_0_4_1_ {
    dependencies = mapFeatures features ([ cfg_if_0_1_3 ]);
    features = mkFeatures (features.log_0_4_1 or {});
  };
  log_0_4_1_features = f: updateFeatures f (rec {
    cfg_if_0_1_3.default = true;
    log_0_4_1.default = (f.log_0_4_1.default or true);
  }) [ cfg_if_0_1_3_features ];
  memchr_1_0_2 = { features?(memchr_1_0_2_features {}) }: memchr_1_0_2_ {
    dependencies = mapFeatures features ([ ]
      ++ (if features.memchr_1_0_2.libc or false then [ libc_0_2_40 ] else []));
    features = mkFeatures (features.memchr_1_0_2 or {});
  };
  memchr_1_0_2_features = f: updateFeatures f (rec {
    libc_0_2_40.default = (f.libc_0_2_40.default or false);
    libc_0_2_40.use_std =
      (f.libc_0_2_40.use_std or false) ||
      (memchr_1_0_2.use_std or false) ||
      (f.memchr_1_0_2.use_std or false);
    memchr_1_0_2.default = (f.memchr_1_0_2.default or true);
    memchr_1_0_2.libc =
      (f.memchr_1_0_2.libc or false) ||
      (f.memchr_1_0_2.default or false) ||
      (memchr_1_0_2.default or false) ||
      (f.memchr_1_0_2.use_std or false) ||
      (memchr_1_0_2.use_std or false);
    memchr_1_0_2.use_std =
      (f.memchr_1_0_2.use_std or false) ||
      (f.memchr_1_0_2.default or false) ||
      (memchr_1_0_2.default or false);
  }) [ libc_0_2_40_features ];
  nix_0_5_1 = { features?(nix_0_5_1_features {}) }: nix_0_5_1_ {
    dependencies = mapFeatures features ([ bitflags_0_4_0 libc_0_2_40 ]);
    features = mkFeatures (features.nix_0_5_1 or {});
  };
  nix_0_5_1_features = f: updateFeatures f (rec {
    bitflags_0_4_0.default = true;
    libc_0_2_40.default = true;
    nix_0_5_1.default = (f.nix_0_5_1.default or true);
  }) [ bitflags_0_4_0_features libc_0_2_40_features ];
  nom_3_2_1 = { features?(nom_3_2_1_features {}) }: nom_3_2_1_ {
    dependencies = mapFeatures features ([ memchr_1_0_2 ]);
    features = mkFeatures (features.nom_3_2_1 or {});
  };
  nom_3_2_1_features = f: updateFeatures f (rec {
    memchr_1_0_2.default = (f.memchr_1_0_2.default or false);
    memchr_1_0_2.use_std =
      (f.memchr_1_0_2.use_std or false) ||
      (nom_3_2_1.std or false) ||
      (f.nom_3_2_1.std or false);
    nom_3_2_1.compiler_error =
      (f.nom_3_2_1.compiler_error or false) ||
      (f.nom_3_2_1.nightly or false) ||
      (nom_3_2_1.nightly or false);
    nom_3_2_1.default = (f.nom_3_2_1.default or true);
    nom_3_2_1.lazy_static =
      (f.nom_3_2_1.lazy_static or false) ||
      (f.nom_3_2_1.regexp_macros or false) ||
      (nom_3_2_1.regexp_macros or false);
    nom_3_2_1.regex =
      (f.nom_3_2_1.regex or false) ||
      (f.nom_3_2_1.regexp or false) ||
      (nom_3_2_1.regexp or false);
    nom_3_2_1.regexp =
      (f.nom_3_2_1.regexp or false) ||
      (f.nom_3_2_1.regexp_macros or false) ||
      (nom_3_2_1.regexp_macros or false);
    nom_3_2_1.std =
      (f.nom_3_2_1.std or false) ||
      (f.nom_3_2_1.default or false) ||
      (nom_3_2_1.default or false);
    nom_3_2_1.stream =
      (f.nom_3_2_1.stream or false) ||
      (f.nom_3_2_1.default or false) ||
      (nom_3_2_1.default or false);
  }) [ memchr_1_0_2_features ];
  num_integer_0_1_38 = { features?(num_integer_0_1_38_features {}) }: num_integer_0_1_38_ {
    dependencies = mapFeatures features ([ num_traits_0_2_4 ]);
    features = mkFeatures (features.num_integer_0_1_38 or {});
  };
  num_integer_0_1_38_features = f: updateFeatures f (rec {
    num_integer_0_1_38.default = (f.num_integer_0_1_38.default or true);
    num_integer_0_1_38.std =
      (f.num_integer_0_1_38.std or false) ||
      (f.num_integer_0_1_38.default or false) ||
      (num_integer_0_1_38.default or false);
    num_traits_0_2_4.default = (f.num_traits_0_2_4.default or false);
    num_traits_0_2_4.i128 =
      (f.num_traits_0_2_4.i128 or false) ||
      (num_integer_0_1_38.i128 or false) ||
      (f.num_integer_0_1_38.i128 or false);
    num_traits_0_2_4.std =
      (f.num_traits_0_2_4.std or false) ||
      (num_integer_0_1_38.std or false) ||
      (f.num_integer_0_1_38.std or false);
  }) [ num_traits_0_2_4_features ];
  num_traits_0_2_4 = { features?(num_traits_0_2_4_features {}) }: num_traits_0_2_4_ {
    features = mkFeatures (features.num_traits_0_2_4 or {});
  };
  num_traits_0_2_4_features = f: updateFeatures f (rec {
    num_traits_0_2_4.default = (f.num_traits_0_2_4.default or true);
    num_traits_0_2_4.std =
      (f.num_traits_0_2_4.std or false) ||
      (f.num_traits_0_2_4.default or false) ||
      (num_traits_0_2_4.default or false);
  }) [];
  proc_macro2_0_3_8 = { features?(proc_macro2_0_3_8_features {}) }: proc_macro2_0_3_8_ {
    dependencies = mapFeatures features ([ unicode_xid_0_1_0 ]);
    features = mkFeatures (features.proc_macro2_0_3_8 or {});
  };
  proc_macro2_0_3_8_features = f: updateFeatures f (rec {
    proc_macro2_0_3_8.default = (f.proc_macro2_0_3_8.default or true);
    proc_macro2_0_3_8.proc-macro =
      (f.proc_macro2_0_3_8.proc-macro or false) ||
      (f.proc_macro2_0_3_8.default or false) ||
      (proc_macro2_0_3_8.default or false) ||
      (f.proc_macro2_0_3_8.nightly or false) ||
      (proc_macro2_0_3_8.nightly or false);
    unicode_xid_0_1_0.default = true;
  }) [ unicode_xid_0_1_0_features ];
  quote_0_3_15 = { features?(quote_0_3_15_features {}) }: quote_0_3_15_ {};
  quote_0_3_15_features = f: updateFeatures f (rec {
    quote_0_3_15.default = (f.quote_0_3_15.default or true);
  }) [];
  quote_0_5_2 = { features?(quote_0_5_2_features {}) }: quote_0_5_2_ {
    dependencies = mapFeatures features ([ proc_macro2_0_3_8 ]);
    features = mkFeatures (features.quote_0_5_2 or {});
  };
  quote_0_5_2_features = f: updateFeatures f (rec {
    proc_macro2_0_3_8.default = (f.proc_macro2_0_3_8.default or false);
    proc_macro2_0_3_8.proc-macro =
      (f.proc_macro2_0_3_8.proc-macro or false) ||
      (quote_0_5_2.proc-macro or false) ||
      (f.quote_0_5_2.proc-macro or false);
    quote_0_5_2.default = (f.quote_0_5_2.default or true);
    quote_0_5_2.proc-macro =
      (f.quote_0_5_2.proc-macro or false) ||
      (f.quote_0_5_2.default or false) ||
      (quote_0_5_2.default or false);
  }) [ proc_macro2_0_3_8_features ];
  rand_0_4_2 = { features?(rand_0_4_2_features {}) }: rand_0_4_2_ {
    dependencies = (if kernel == "fuchsia" then mapFeatures features ([ fuchsia_zircon_0_3_3 ]) else [])
      ++ (if (kernel == "linux" || kernel == "darwin") then mapFeatures features ([ ]
      ++ (if features.rand_0_4_2.libc or false then [ libc_0_2_40 ] else [])) else [])
      ++ (if kernel == "windows" then mapFeatures features ([ winapi_0_3_4 ]) else []);
    features = mkFeatures (features.rand_0_4_2 or {});
  };
  rand_0_4_2_features = f: updateFeatures f (rec {
    fuchsia_zircon_0_3_3.default = true;
    libc_0_2_40.default = true;
    rand_0_4_2.default = (f.rand_0_4_2.default or true);
    rand_0_4_2.i128_support =
      (f.rand_0_4_2.i128_support or false) ||
      (f.rand_0_4_2.nightly or false) ||
      (rand_0_4_2.nightly or false);
    rand_0_4_2.libc =
      (f.rand_0_4_2.libc or false) ||
      (f.rand_0_4_2.std or false) ||
      (rand_0_4_2.std or false);
    rand_0_4_2.std =
      (f.rand_0_4_2.std or false) ||
      (f.rand_0_4_2.default or false) ||
      (rand_0_4_2.default or false);
    winapi_0_3_4.default = true;
    winapi_0_3_4.minwindef = true;
    winapi_0_3_4.ntsecapi = true;
    winapi_0_3_4.profileapi = true;
    winapi_0_3_4.winnt = true;
  }) [ fuchsia_zircon_0_3_3_features libc_0_2_40_features winapi_0_3_4_features ];
  redox_syscall_0_1_37 = { features?(redox_syscall_0_1_37_features {}) }: redox_syscall_0_1_37_ {};
  redox_syscall_0_1_37_features = f: updateFeatures f (rec {
    redox_syscall_0_1_37.default = (f.redox_syscall_0_1_37.default or true);
  }) [];
  rust_scripts_0_1_0 = { features?(rust_scripts_0_1_0_features {}) }: rust_scripts_0_1_0_ {
    dependencies = mapFeatures features ([ chrono_0_4_2 dialog_0_1_0 error_chain_0_11_0 kairos_0_1_0 lazy_static_1_0_0 serde_1_0_55 serde_derive_1_0_55 serde_yaml_0_7_4 task_hookrs_0_5_0 uuid_0_6_3 ]);
  };
  rust_scripts_0_1_0_features = f: updateFeatures f (rec {
    chrono_0_4_2.default = true;
    dialog_0_1_0.default = true;
    error_chain_0_11_0.default = true;
    kairos_0_1_0.default = true;
    lazy_static_1_0_0.default = true;
    rust_scripts_0_1_0.default = (f.rust_scripts_0_1_0.default or true);
    serde_1_0_55.default = true;
    serde_derive_1_0_55.default = true;
    serde_yaml_0_7_4.default = true;
    task_hookrs_0_5_0.default = true;
    uuid_0_6_3.default = true;
  }) [ chrono_0_4_2_features dialog_0_1_0_features error_chain_0_11_0_features kairos_0_1_0_features lazy_static_1_0_0_features serde_1_0_55_features serde_derive_1_0_55_features serde_yaml_0_7_4_features task_hookrs_0_5_0_features uuid_0_6_3_features ];
  rustc_demangle_0_1_8 = { features?(rustc_demangle_0_1_8_features {}) }: rustc_demangle_0_1_8_ {};
  rustc_demangle_0_1_8_features = f: updateFeatures f (rec {
    rustc_demangle_0_1_8.default = (f.rustc_demangle_0_1_8.default or true);
  }) [];
  rustyline_1_0_0 = { features?(rustyline_1_0_0_features {}) }: rustyline_1_0_0_ {
    dependencies = mapFeatures features ([ encode_unicode_0_1_3 libc_0_2_40 unicode_width_0_1_4 ])
      ++ (if (kernel == "linux" || kernel == "darwin") then mapFeatures features ([ nix_0_5_1 ]) else [])
      ++ (if kernel == "windows" then mapFeatures features ([ kernel32_sys_0_2_2 winapi_0_2_8 ]) else []);
  };
  rustyline_1_0_0_features = f: updateFeatures f (rec {
    encode_unicode_0_1_3.default = true;
    kernel32_sys_0_2_2.default = true;
    libc_0_2_40.default = true;
    nix_0_5_1.default = true;
    rustyline_1_0_0.default = (f.rustyline_1_0_0.default or true);
    unicode_width_0_1_4.default = true;
    winapi_0_2_8.default = true;
  }) [ encode_unicode_0_1_3_features libc_0_2_40_features unicode_width_0_1_4_features nix_0_5_1_features kernel32_sys_0_2_2_features winapi_0_2_8_features ];
  serde_1_0_55 = { features?(serde_1_0_55_features {}) }: serde_1_0_55_ {
    dependencies = mapFeatures features ([]);
    features = mkFeatures (features.serde_1_0_55 or {});
  };
  serde_1_0_55_features = f: updateFeatures f (rec {
    serde_1_0_55.default = (f.serde_1_0_55.default or true);
    serde_1_0_55.serde_derive =
      (f.serde_1_0_55.serde_derive or false) ||
      (f.serde_1_0_55.derive or false) ||
      (serde_1_0_55.derive or false);
    serde_1_0_55.std =
      (f.serde_1_0_55.std or false) ||
      (f.serde_1_0_55.default or false) ||
      (serde_1_0_55.default or false);
    serde_1_0_55.unstable =
      (f.serde_1_0_55.unstable or false) ||
      (f.serde_1_0_55.alloc or false) ||
      (serde_1_0_55.alloc or false);
  }) [];
  serde_derive_1_0_55 = { features?(serde_derive_1_0_55_features {}) }: serde_derive_1_0_55_ {
    dependencies = mapFeatures features ([ proc_macro2_0_3_8 quote_0_5_2 syn_0_13_10 ]);
    features = mkFeatures (features.serde_derive_1_0_55 or {});
  };
  serde_derive_1_0_55_features = f: updateFeatures f (rec {
    proc_macro2_0_3_8.default = true;
    quote_0_5_2.default = true;
    serde_derive_1_0_55.default = (f.serde_derive_1_0_55.default or true);
    syn_0_13_10.default = true;
    syn_0_13_10.visit = true;
  }) [ proc_macro2_0_3_8_features quote_0_5_2_features syn_0_13_10_features ];
  serde_json_1_0_17 = { features?(serde_json_1_0_17_features {}) }: serde_json_1_0_17_ {
    dependencies = mapFeatures features ([ dtoa_0_4_2 itoa_0_4_1 serde_1_0_55 ]);
    features = mkFeatures (features.serde_json_1_0_17 or {});
  };
  serde_json_1_0_17_features = f: updateFeatures f (rec {
    dtoa_0_4_2.default = true;
    itoa_0_4_1.default = true;
    serde_1_0_55.default = true;
    serde_json_1_0_17.default = (f.serde_json_1_0_17.default or true);
    serde_json_1_0_17.linked-hash-map =
      (f.serde_json_1_0_17.linked-hash-map or false) ||
      (f.serde_json_1_0_17.preserve_order or false) ||
      (serde_json_1_0_17.preserve_order or false);
  }) [ dtoa_0_4_2_features itoa_0_4_1_features serde_1_0_55_features ];
  serde_yaml_0_7_4 = { features?(serde_yaml_0_7_4_features {}) }: serde_yaml_0_7_4_ {
    dependencies = mapFeatures features ([ dtoa_0_4_2 linked_hash_map_0_5_1 serde_1_0_55 yaml_rust_0_4_0 ]);
  };
  serde_yaml_0_7_4_features = f: updateFeatures f (rec {
    dtoa_0_4_2.default = true;
    linked_hash_map_0_5_1.default = true;
    serde_1_0_55.default = true;
    serde_yaml_0_7_4.default = (f.serde_yaml_0_7_4.default or true);
    yaml_rust_0_4_0.default = true;
  }) [ dtoa_0_4_2_features linked_hash_map_0_5_1_features serde_1_0_55_features yaml_rust_0_4_0_features ];
  syn_0_11_11 = { features?(syn_0_11_11_features {}) }: syn_0_11_11_ {
    dependencies = mapFeatures features ([ ]
      ++ (if features.syn_0_11_11.quote or false then [ quote_0_3_15 ] else [])
      ++ (if features.syn_0_11_11.synom or false then [ synom_0_11_3 ] else [])
      ++ (if features.syn_0_11_11.unicode-xid or false then [ unicode_xid_0_0_4 ] else []));
    features = mkFeatures (features.syn_0_11_11 or {});
  };
  syn_0_11_11_features = f: updateFeatures f (rec {
    quote_0_3_15.default = true;
    syn_0_11_11.default = (f.syn_0_11_11.default or true);
    syn_0_11_11.parsing =
      (f.syn_0_11_11.parsing or false) ||
      (f.syn_0_11_11.default or false) ||
      (syn_0_11_11.default or false);
    syn_0_11_11.printing =
      (f.syn_0_11_11.printing or false) ||
      (f.syn_0_11_11.default or false) ||
      (syn_0_11_11.default or false);
    syn_0_11_11.quote =
      (f.syn_0_11_11.quote or false) ||
      (f.syn_0_11_11.printing or false) ||
      (syn_0_11_11.printing or false);
    syn_0_11_11.synom =
      (f.syn_0_11_11.synom or false) ||
      (f.syn_0_11_11.parsing or false) ||
      (syn_0_11_11.parsing or false);
    syn_0_11_11.unicode-xid =
      (f.syn_0_11_11.unicode-xid or false) ||
      (f.syn_0_11_11.parsing or false) ||
      (syn_0_11_11.parsing or false);
    synom_0_11_3.default = true;
    unicode_xid_0_0_4.default = true;
  }) [ quote_0_3_15_features synom_0_11_3_features unicode_xid_0_0_4_features ];
  syn_0_13_10 = { features?(syn_0_13_10_features {}) }: syn_0_13_10_ {
    dependencies = mapFeatures features ([ proc_macro2_0_3_8 unicode_xid_0_1_0 ]
      ++ (if features.syn_0_13_10.quote or false then [ quote_0_5_2 ] else []));
    features = mkFeatures (features.syn_0_13_10 or {});
  };
  syn_0_13_10_features = f: updateFeatures f (rec {
    proc_macro2_0_3_8.default = (f.proc_macro2_0_3_8.default or false);
    proc_macro2_0_3_8.proc-macro =
      (f.proc_macro2_0_3_8.proc-macro or false) ||
      (syn_0_13_10.proc-macro or false) ||
      (f.syn_0_13_10.proc-macro or false);
    quote_0_5_2.default = (f.quote_0_5_2.default or false);
    quote_0_5_2.proc-macro =
      (f.quote_0_5_2.proc-macro or false) ||
      (syn_0_13_10.proc-macro or false) ||
      (f.syn_0_13_10.proc-macro or false);
    syn_0_13_10.clone-impls =
      (f.syn_0_13_10.clone-impls or false) ||
      (f.syn_0_13_10.default or false) ||
      (syn_0_13_10.default or false);
    syn_0_13_10.default = (f.syn_0_13_10.default or true);
    syn_0_13_10.derive =
      (f.syn_0_13_10.derive or false) ||
      (f.syn_0_13_10.default or false) ||
      (syn_0_13_10.default or false);
    syn_0_13_10.parsing =
      (f.syn_0_13_10.parsing or false) ||
      (f.syn_0_13_10.default or false) ||
      (syn_0_13_10.default or false);
    syn_0_13_10.printing =
      (f.syn_0_13_10.printing or false) ||
      (f.syn_0_13_10.default or false) ||
      (syn_0_13_10.default or false);
    syn_0_13_10.proc-macro =
      (f.syn_0_13_10.proc-macro or false) ||
      (f.syn_0_13_10.default or false) ||
      (syn_0_13_10.default or false);
    syn_0_13_10.quote =
      (f.syn_0_13_10.quote or false) ||
      (f.syn_0_13_10.printing or false) ||
      (syn_0_13_10.printing or false);
    unicode_xid_0_1_0.default = true;
  }) [ proc_macro2_0_3_8_features quote_0_5_2_features unicode_xid_0_1_0_features ];
  synom_0_11_3 = { features?(synom_0_11_3_features {}) }: synom_0_11_3_ {
    dependencies = mapFeatures features ([ unicode_xid_0_0_4 ]);
  };
  synom_0_11_3_features = f: updateFeatures f (rec {
    synom_0_11_3.default = (f.synom_0_11_3.default or true);
    unicode_xid_0_0_4.default = true;
  }) [ unicode_xid_0_0_4_features ];
  task_hookrs_0_5_0 = { features?(task_hookrs_0_5_0_features {}) }: task_hookrs_0_5_0_ {
    dependencies = mapFeatures features ([ chrono_0_4_2 derive_builder_0_5_1 error_chain_0_11_0 log_0_4_1 serde_1_0_55 serde_derive_1_0_55 serde_json_1_0_17 uuid_0_6_3 ]);
  };
  task_hookrs_0_5_0_features = f: updateFeatures f (rec {
    chrono_0_4_2.default = true;
    derive_builder_0_5_1.default = true;
    error_chain_0_11_0.default = true;
    log_0_4_1.default = true;
    serde_1_0_55.default = true;
    serde_derive_1_0_55.default = true;
    serde_json_1_0_17.default = true;
    task_hookrs_0_5_0.default = (f.task_hookrs_0_5_0.default or true);
    uuid_0_6_3.default = true;
    uuid_0_6_3.serde = true;
    uuid_0_6_3.v4 = true;
  }) [ chrono_0_4_2_features derive_builder_0_5_1_features error_chain_0_11_0_features log_0_4_1_features serde_1_0_55_features serde_derive_1_0_55_features serde_json_1_0_17_features uuid_0_6_3_features ];
  termios_0_3_0 = { features?(termios_0_3_0_features {}) }: termios_0_3_0_ {
    dependencies = mapFeatures features ([ libc_0_2_40 ]);
  };
  termios_0_3_0_features = f: updateFeatures f (rec {
    libc_0_2_40.default = true;
    termios_0_3_0.default = (f.termios_0_3_0.default or true);
  }) [ libc_0_2_40_features ];
  time_0_1_40 = { features?(time_0_1_40_features {}) }: time_0_1_40_ {
    dependencies = mapFeatures features ([ libc_0_2_40 ])
      ++ (if kernel == "redox" then mapFeatures features ([ redox_syscall_0_1_37 ]) else [])
      ++ (if kernel == "windows" then mapFeatures features ([ winapi_0_3_4 ]) else []);
  };
  time_0_1_40_features = f: updateFeatures f (rec {
    libc_0_2_40.default = true;
    redox_syscall_0_1_37.default = true;
    time_0_1_40.default = (f.time_0_1_40.default or true);
    winapi_0_3_4.default = true;
    winapi_0_3_4.minwinbase = true;
    winapi_0_3_4.minwindef = true;
    winapi_0_3_4.ntdef = true;
    winapi_0_3_4.profileapi = true;
    winapi_0_3_4.std = true;
    winapi_0_3_4.sysinfoapi = true;
    winapi_0_3_4.timezoneapi = true;
  }) [ libc_0_2_40_features redox_syscall_0_1_37_features winapi_0_3_4_features ];
  unicode_width_0_1_4 = { features?(unicode_width_0_1_4_features {}) }: unicode_width_0_1_4_ {
    features = mkFeatures (features.unicode_width_0_1_4 or {});
  };
  unicode_width_0_1_4_features = f: updateFeatures f (rec {
    unicode_width_0_1_4.default = (f.unicode_width_0_1_4.default or true);
  }) [];
  unicode_xid_0_0_4 = { features?(unicode_xid_0_0_4_features {}) }: unicode_xid_0_0_4_ {
    features = mkFeatures (features.unicode_xid_0_0_4 or {});
  };
  unicode_xid_0_0_4_features = f: updateFeatures f (rec {
    unicode_xid_0_0_4.default = (f.unicode_xid_0_0_4.default or true);
  }) [];
  unicode_xid_0_1_0 = { features?(unicode_xid_0_1_0_features {}) }: unicode_xid_0_1_0_ {
    features = mkFeatures (features.unicode_xid_0_1_0 or {});
  };
  unicode_xid_0_1_0_features = f: updateFeatures f (rec {
    unicode_xid_0_1_0.default = (f.unicode_xid_0_1_0.default or true);
  }) [];
  uuid_0_6_3 = { features?(uuid_0_6_3_features {}) }: uuid_0_6_3_ {
    dependencies = mapFeatures features ([ cfg_if_0_1_3 ]
      ++ (if features.uuid_0_6_3.rand or false then [ rand_0_4_2 ] else [])
      ++ (if features.uuid_0_6_3.serde or false then [ serde_1_0_55 ] else []));
    features = mkFeatures (features.uuid_0_6_3 or {});
  };
  uuid_0_6_3_features = f: updateFeatures f (rec {
    cfg_if_0_1_3.default = true;
    rand_0_4_2.default = true;
    serde_1_0_55.default = (f.serde_1_0_55.default or false);
    uuid_0_6_3.default = (f.uuid_0_6_3.default or true);
    uuid_0_6_3.md5 =
      (f.uuid_0_6_3.md5 or false) ||
      (f.uuid_0_6_3.v3 or false) ||
      (uuid_0_6_3.v3 or false);
    uuid_0_6_3.rand =
      (f.uuid_0_6_3.rand or false) ||
      (f.uuid_0_6_3.v3 or false) ||
      (uuid_0_6_3.v3 or false) ||
      (f.uuid_0_6_3.v4 or false) ||
      (uuid_0_6_3.v4 or false) ||
      (f.uuid_0_6_3.v5 or false) ||
      (uuid_0_6_3.v5 or false);
    uuid_0_6_3.serde =
      (f.uuid_0_6_3.serde or false) ||
      (f.uuid_0_6_3.playground or false) ||
      (uuid_0_6_3.playground or false);
    uuid_0_6_3.sha1 =
      (f.uuid_0_6_3.sha1 or false) ||
      (f.uuid_0_6_3.v5 or false) ||
      (uuid_0_6_3.v5 or false);
    uuid_0_6_3.std =
      (f.uuid_0_6_3.std or false) ||
      (f.uuid_0_6_3.default or false) ||
      (uuid_0_6_3.default or false) ||
      (f.uuid_0_6_3.use_std or false) ||
      (uuid_0_6_3.use_std or false);
    uuid_0_6_3.v1 =
      (f.uuid_0_6_3.v1 or false) ||
      (f.uuid_0_6_3.playground or false) ||
      (uuid_0_6_3.playground or false);
    uuid_0_6_3.v3 =
      (f.uuid_0_6_3.v3 or false) ||
      (f.uuid_0_6_3.playground or false) ||
      (uuid_0_6_3.playground or false);
    uuid_0_6_3.v4 =
      (f.uuid_0_6_3.v4 or false) ||
      (f.uuid_0_6_3.playground or false) ||
      (uuid_0_6_3.playground or false);
    uuid_0_6_3.v5 =
      (f.uuid_0_6_3.v5 or false) ||
      (f.uuid_0_6_3.playground or false) ||
      (uuid_0_6_3.playground or false);
  }) [ cfg_if_0_1_3_features rand_0_4_2_features serde_1_0_55_features ];
  winapi_0_2_8 = { features?(winapi_0_2_8_features {}) }: winapi_0_2_8_ {};
  winapi_0_2_8_features = f: updateFeatures f (rec {
    winapi_0_2_8.default = (f.winapi_0_2_8.default or true);
  }) [];
  winapi_0_3_4 = { features?(winapi_0_3_4_features {}) }: winapi_0_3_4_ {
    dependencies = (if kernel == "i686-pc-windows-gnu" then mapFeatures features ([ winapi_i686_pc_windows_gnu_0_4_0 ]) else [])
      ++ (if kernel == "x86_64-pc-windows-gnu" then mapFeatures features ([ winapi_x86_64_pc_windows_gnu_0_4_0 ]) else []);
    features = mkFeatures (features.winapi_0_3_4 or {});
  };
  winapi_0_3_4_features = f: updateFeatures f (rec {
    winapi_0_3_4.default = (f.winapi_0_3_4.default or true);
    winapi_i686_pc_windows_gnu_0_4_0.default = true;
    winapi_x86_64_pc_windows_gnu_0_4_0.default = true;
  }) [ winapi_i686_pc_windows_gnu_0_4_0_features winapi_x86_64_pc_windows_gnu_0_4_0_features ];
  winapi_build_0_1_1 = { features?(winapi_build_0_1_1_features {}) }: winapi_build_0_1_1_ {};
  winapi_build_0_1_1_features = f: updateFeatures f (rec {
    winapi_build_0_1_1.default = (f.winapi_build_0_1_1.default or true);
  }) [];
  winapi_i686_pc_windows_gnu_0_4_0 = { features?(winapi_i686_pc_windows_gnu_0_4_0_features {}) }: winapi_i686_pc_windows_gnu_0_4_0_ {};
  winapi_i686_pc_windows_gnu_0_4_0_features = f: updateFeatures f (rec {
    winapi_i686_pc_windows_gnu_0_4_0.default = (f.winapi_i686_pc_windows_gnu_0_4_0.default or true);
  }) [];
  winapi_x86_64_pc_windows_gnu_0_4_0 = { features?(winapi_x86_64_pc_windows_gnu_0_4_0_features {}) }: winapi_x86_64_pc_windows_gnu_0_4_0_ {};
  winapi_x86_64_pc_windows_gnu_0_4_0_features = f: updateFeatures f (rec {
    winapi_x86_64_pc_windows_gnu_0_4_0.default = (f.winapi_x86_64_pc_windows_gnu_0_4_0.default or true);
  }) [];
  yaml_rust_0_4_0 = { features?(yaml_rust_0_4_0_features {}) }: yaml_rust_0_4_0_ {
    dependencies = mapFeatures features ([ linked_hash_map_0_5_1 ]);
  };
  yaml_rust_0_4_0_features = f: updateFeatures f (rec {
    linked_hash_map_0_5_1.default = true;
    yaml_rust_0_4_0.default = (f.yaml_rust_0_4_0.default or true);
  }) [ linked_hash_map_0_5_1_features ];
}
