[package]
name = "habitask"
version = "0.1.0"
authors = ["Malte Brandy <malte.brandy@maralorn.de>"]

[dependencies]
task-hookrs = { git = "https://git.darmstadt.ccc.de/maralorn/task-hookrs.git"}
error-chain = "0.11.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.8"
hyper = "0.11"
config = "0.9.0"
