groups:
   - name: rules
     rules:
        - alert: probe_timeout
          expr: probe_success == 0
          for: 60m
          labels:
             severity: critical
          annotations:
             description: '{{ $labels.instance }} probe {{ $labels.job}} failed.'
        - alert: nixpkgs
          expr: hydra_job_failed == 1
          for: 2h
          labels:
             severity: warning
          annotations:
             description: 'hydra build {{ $labels.packageName }} on nixpkgs branch {{ $labels.jobset }} failed.'
        - alert: node_down
          expr: 'up{name!="exporter apollo",instance!="hydra.nixos.org:443"} == 0'
          for: 5m
          labels:
             severity: critical
          annotations:
             description: '{{ $labels.name }} is not reachable.'
        - alert: systemd_service_failed
          expr: node_systemd_unit_state{state="failed",exported_name!~"configure-printer.*"} == 1
          for: 5m
          labels:
             severity: critical
          annotations:
             description: 'service {{$labels.exported_name}} on {{$labels.name}} failed.'
