# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/disk" =
    {
      device = "/dev/disk/by-uuid/ac20f7bf-387e-42b0-b3df-b14163f45913";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."crypted-nixos".device = "/dev/disk/by-uuid/2518e0e0-c263-40bc-b378-419832dc62cc";

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/ac20f7bf-387e-42b0-b3df-b14163f45913";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/ac20f7bf-387e-42b0-b3df-b14163f45913";
      fsType = "btrfs";
      options = [ "subvol=boot" ];
    };

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/C41C-0C8E";
      fsType = "vfat";
    };

  swapDevices = [ ];

}
