substitutions:
  macsuffix: b27a0c

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  manual_ip:
    static_ip: 192.168.178.21
    gateway: 192.168.178.1
    subnet: 255.255.255.0

<<: !include ../includes/wt32-eth01.yaml
<<: !include ../includes/base.yaml
