{
 "title": "Health Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Unreachable nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance!=\"apollo:9100\"} +1 == 1",
     "legendFormat": "{{job}} - {{ instance }}"
    }
   ]
  },
  {
   "title": "Failed Systemd Units",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"failed\"} > 0",
     "legendFormat": "{{exported_name}} on {{ name}}"
    }
   ]
  },
  {
   "title": "Nixpkgs Build Failures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hydra_job_failed > 0", "legendFormat": "{{exported_job}} on {{jobset}}" }
   ]
  },
  {
   "title": "Probe Timeouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "1 - probe_success == 1", "legendFormat": "{{job}} against {{instance}}" }
   ]
  }
 ]
}