default: all

all: links

links:
	ln -sfT ~/data/aktuell/it/config/nixos ~/.config/nixpkgs/config
	ln -sfT data/aktuell/it/secrets/password-store ~/.password-store
	ln -sfT data/aktuell/it/secrets/gnupg ~/.gnupg
