{
 "title": "Health Status",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "type": "text", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 }, "options": { "content": "@BADGES@" } },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Active alerts",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{alert_type=\"infrastructure\"}",
     "legendFormat": "{{alertname}} for {{name}} ({{alertstate}})"
    }
   ]
  },
  {
   "title": "Unreachable nodes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance!=\"apollo:9100\"} +1 == 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Probe Timeouts",
   "type": "graph",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "1 - probe_success == 1", "legendFormat": "{{job}} against {{instance}}" }
   ]
  },
  {
   "title": "Failed Systemd Units",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"failed\",exported_name!~\"configure-printer.*\"} > 0",
     "legendFormat": "{{exported_name}} from {{ name }}"
    }
   ]
  },
  {
   "title": "Nixpkgs Build Failures",
   "type": "graph",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hydra_job_failed > 0", "legendFormat": "{{packageName}} on {{jobset}}" }
   ]
  },
  {
   "title": "Last failed hydra builds",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "hydra_job_completion_time * hydra_job_failed * 1000 > 0",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}